### ISSUE TITLE
Secure simpleserver.cpp example

### ISSUE THREAD

**Issue by ChicagoSchooler** [cinemast/libjson-rpc-cpp#115]
Great library!  Took only minutes to install and integrate into my server.

I tried [this suggested modification](https://github.com/cinemast/libjson-rpc-cpp/issues/10#issuecomment-17807455), but it appears as if simpleserver.cpp has changed somewhat, and I'm unsure how to implement the suggestion.

Could you provide a quick example on how to use SSL for simpleserver.cpp?

**Comment by cinemast** [comment]
Hi!

Thank you. You have to provide a certificate file and a key file to the constructor of the HttpServer:

https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/test/test_connector_http.cpp#L206.

For the client just use https instead of http for the url.

**Comment by ChicagoSchooler** [comment]
Ah, of course.

Thank you!
