### ISSUE TITLE
Procedure details

### ISSUE THREAD

**Issue by ChicagoSchooler** [cinemast/libjson-rpc-cpp#116]
I'm caught on a small issue.  I'm binding with:

```c++
this->bindAndAddMethod(
	jsonrpc::Procedure(
		"getbalances", jsonrpc::PARAMS_BY_NAME, 
		jsonrpc::JSON_ARRAY, "accts", 
		jsonrpc::JSON_OBJECT, NULL
	), 
	&rpc_server::getbalances
);
```

this is my call:

```bash
curl -g -d '{"jsonrpc":"2.0","method":"getbalances","id":1,"params":{"accts":["QR4Q95AFy+kkqz2YC6ZC+ETiF/3LmIA7BHSDU831FxA"]}}' https://localhost:8001 -k
```

and here's the error:

```json
{"error":{"code":-32602,"message":"INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised"},"id":1,"jsonrpc":"2.0"}
```

Why is that binding and call giving this error?

**Comment by ChicagoSchooler** [comment]
Strings work.  I haven't tested objects.

Is this something particular to arrays?

**Comment by cinemast** [comment]
No problem. Just ask anytime :)

Do you know about stubgenerator tool? This avoids such errors.

**Comment by ChicagoSchooler** [comment]
Saw that, and I highly recommend it.

Thanks again for such a great library!  I completed everything I need yesterday.  Probably my fastest implementation yet.

A library like this is very rare.
