### ISSUE TITLE
How to install libjson-rpc-cpp under windows 

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#121]
Dear all
Could you please tell me how to install libjson-rpc-cpp on windows 7
Thanks in advance

**Comment by cinemast** [comment]
As described in the README: Download and install https://spiessknafl.at/libjson-rpc-cpp/libjson-rpc-cpp-0.5.0-win32.exe

**Comment by Nouri1111** [comment]
I's installed and when I executed the command: jsonrpcstub spec.json --cpp-server=AbstractStubServer --cpp-client=StubClient
The below error message displayed:
jsonpcstub a cessé de fonctionner
I think at first that I delited the the install folder without make unstlall :/  then installed again tne .exe
Is there any way to fix this problem 
thanks in advance
Merci d'a

**Comment by cinemast** [comment]
I am not sure what the french error message says, but I just tried a fresh install of the [lastest exe](https://spiessknafl.at/libjson-rpc-cpp/libjson-rpc-cpp-0.5.0-win32.exe) under window7. (Check the option to add libjson-rpc-cpp to the PATH of all users, during the setup wizard). If you don't add it to the path. You have to execute jsonrpcstub from the installation directory of libjson-rpc-cpp (`C:\Program Files (x86)\libjson-rpc-cpp 0.5.0\bin`)

I hope this fixes your situation. 

About the borken installation: If uninstall.exe inside the installation directory does not work, just delete the folder.

**Comment by loreilei** [comment]
Hi Peter the french error basically translate to "jsonrpccpp stopped working". This message often appears on windows when a segfault happened and the software crashed.

**Comment by cinemast** [comment]
Ah.. thanks Alexandre.

Well @Nouri1111 could you please describe exactly, which steps lead to the situation?

**Comment by cinemast** [comment]
@Nouri1111 since we haven't heard back from you, I will close this issue for now, assuming you figured out the problem. Please re-open this issue if you have further questions.
