### ISSUE TITLE
Is there any example jsonrpc with TCP/IP

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#122]
Dear all, 
Could you please tell me if jsonrpc based on http or TCP/IP 
I'm looking for an example with TCP/IP
could you help me pelase

**Comment by cinemast** [comment]
Hi!

Currently only HTTP is supported on the master branch. Thanks to @alexandre-poirot  there will be a pure TCP implementation available soon. A preview version is already available as pull-request under: 

https://github.com/cinemast/libjson-rpc-cpp/pull/120.

He also provided examples for server and client:

https://github.com/Legrandgroup/libjson-rpc-cpp/blob/develop/src/examples/tcpsocketclient.cpp
https://github.com/Legrandgroup/libjson-rpc-cpp/blob/develop/src/examples/tcpsocketserver.cpp

I hope this is what you are looking for.

**Comment by Nouri1111** [comment]
thanks alot for your help
Yes that's what I'm looking for, but after after I compilet the client.cpp,
the below error was displayed:
"client.cpp:9:58: erreur fatale:
jsonrpccpp/client/connectors/tcpsocketclient.h : Aucun fichier ou dossier
de ce type
compilation terminée."
Mean that there are no tcpsocketclient.h, so what I sould do for including
this file
how to compile the demo
thanks in advance


2015-08-04 7:16 GMT-07:00 Peter Spiess-Knafl <notifications@github.com>:

> Hi!
>
> Currently only HTTP is supported on the master branch. Thanks to
> @alexandre-poirot <https://github.com/alexandre-poirot> there will be a
> pure TCP implementation available soon. A preview version is already
> available as pull-request under:
>
> #120 <https://github.com/cinemast/libjson-rpc-cpp/pull/120>.
>
> He also provided examples for server and client:
>
>
> https://github.com/Legrandgroup/libjson-rpc-cpp/blob/develop/src/examples/tcpsocketclient.cpp
>
> https://github.com/Legrandgroup/libjson-rpc-cpp/blob/develop/src/examples/tcpsocketserver.cpp
>
> I hope this is what you are looking for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cinemast/libjson-rpc-cpp/issues/122#issuecomment-127627717>
> .
>



-- 

*Cordialement,*
Noureddine

**Comment by loreilei** [comment]
Just to be sure, did you checkout the "develop" branch before trying to compile ?

**Comment by Nouri1111** [comment]
Yes I cheked and I didn't find this file. I think this branche still not
ready to use with TCP
what do you thinks about, do you have any idea
Thanks in advance

2015-08-04 7:51 GMT-07:00 Alexandre Poirot <notifications@github.com>:

> Just to be sure, did you checkout the "develop" branch before trying to
> compile ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cinemast/libjson-rpc-cpp/issues/122#issuecomment-127639979>
> .
>



-- 

*Cordialement,*
Noureddine

**Comment by loreilei** [comment]
Dumb suggestion of mine. In fact, those tcp socket are not yet merged on cinemast's repo but it is in Legrandgroup's one. Which one did you clone ?

**Comment by Nouri1111** [comment]
this one:
https://github.com/Legrandgroup/libjson-rpc-cpp/tree/develop
it's the right!! or there are ather branche!!

2015-08-04 8:00 GMT-07:00 Alexandre Poirot <notifications@github.com>:

> Dumb suggestion of mine. In fact, those tcp socket are not yet merged on
> cinemast's repo but it is in Legrandgroup's one. Which one did you clone ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cinemast/libjson-rpc-cpp/issues/122#issuecomment-127642270>
> .
>



-- 

*Cordialement,*
Noureddine

**Comment by loreilei** [comment]
Yeah it's that one. Do you see the missing file in your filesystem ?

**Comment by Nouri1111** [comment]
No, under jsonrpccpp/server/connectors/, there a re only the httpserver.h
andd the httpclient.h

2015-08-04 8:09 GMT-07:00 Alexandre Poirot <notifications@github.com>:

> Yeah it's that one. Do you see the missing file in your filesystem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cinemast/libjson-rpc-cpp/issues/122#issuecomment-127644487>
> .
>



-- 

*Cordialement,*
Noureddine

**Comment by cinemast** [comment]
It looks like you did not checkout out the correct branch.

**Comment by Nouri1111** [comment]
So can you send me the link for the correct branche?
Thanks in advance

**Comment by cinemast** [comment]
https://github.com/Legrandgroup/libjson-rpc-cpp/tree/develop

This is it.

```
git clone https://github.com/Legrandgroup/libjson-rpc-cpp.git
git checkout develop
```
