### ISSUE TITLE
Could you please tell me how to cross-compile json-rpc with Yocto

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#123]
Dear all,

**Comment by loreilei** [comment]
I'll guess that the title is the question.

Do a basic bitbake recipe but put the git repository as the source.

It would looks like :
SRC_URI="git://github.com/cinemast/libjson-rpc-cpp.git"
if you want to clone with SSH or
SRC_URI="git://github.com/cinemast/libjson-rpc-cpp.git;protocol=http"
if you want to clone over http.

**Comment by cinemast** [comment]
If you come up with a recipe, I would be very happy about a pull-request. I think this is a very useful enabler for libjson-rpc-cpp on embedded platforms.

**Comment by Nouri1111** [comment]
Thanks to all of you,
below the file .bb that I use

DESCRIPTION = "libjsonrpc"
HOMEPAGE = "https://github.com/cinemast/libjson-rpc-cpp"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://MIT;md5=f3e38c1f1e0db893f5e9a1b4328246d3"
SRC_URI = "git://github.com/cinemast/libjson-rpc-cpp.git \
"
SRCREV = "ce8c0205f2c752d5503ef94749fbc6f4c8d174a2"
S = "${WORKDIR}/git"
inherit autotools



and when I copiled I got the below erros:


NOTE: Preparing runqueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: Function failed: do_install (log file is located at /yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/temp/log.do_install.5074)
ERROR: Logfile of failure stored in: /yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/temp/log.do_install.5074
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Executing shell function do_install
| NOTE: make -j 8 DESTDIR=/yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/image install
| make: *** No rule to make target `install'.  Stop.
| ERROR: oe_runmake failed
| WARNING: /yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/temp/run.do_install.5074:1 exit 1 from
|   exit 1
| ERROR: Function failed: do_install (log file is located at /yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/temp/log.do_install.5074)
ERROR: Task 2 (/yocto_projects/partitions/9/poky/meta-valeo/recipes/2_middleWare/libjson-rpc/libjson-rpc_git.bb, do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 370 tasks of which 367 didn't need to be rerun and 1 failed.
No currently running tasks (370 of 375)

Summary: 1 task failed:
  /yocto_projects/partitions/9/poky/meta-valeo/recipes/2_middleWare/libjson-rpc/libjson-rpc_git.bb, do_install
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.


So what do you think about , could you please tell me how to add the do_install
Thanks in advance

**Comment by loreilei** [comment]
I would have added some dependency to jsoncpp in the recipe. Also, inheriting cmake might helps a bit ?

Can you post the content of the log (/yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/temp/log.do_install.5074) ?

It might helps too.

**Comment by loreilei** [comment]
@cinemast It would be better to push a recipe to yocto's repository than including a bitbake recipe in this one (you know, since recipe will refers to this repo, it will make some kind of loop). Plus, pushing the recipe to yocto's would pack libjson-rpc-cpp with yocto as well.

**Comment by Nouri1111** [comment]
Now I change the .bb file as(I added: inherit pkgconfig cmake)
DESCRIPTION = "libjsonrpc"
HOMEPAGE = "https://github.com/cinemast/libjson-rpc-cpp"

#LICENSE = "GPLv2"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

#PV = "1.16"
PR = "r0"
SRC_URI = "git://github.com/cinemast/libjson-rpc-cpp.git \
"
SRCREV = "ce8c0205f2c752d5503ef94749fbc6f4c8d174a2"
S = "${WORKDIR}/git"
inherit pkgconfig cmake
 Please see below the log file contents: 


Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- HTTP_SERVER: YES
-- HTTP_CLIENT: YES
-- UNIXDOMAINSOCKET_SERVER: YES
-- UNIXDOMAINSOCKET_CLIENT: YES
-- COMPILE_TESTS: YES
-- COMPILE_STUBGEN: YES
-- COMPILE_EXAMPLES: YES
-- Could NOT find jsoncpp (missing:  JSONCPP_LIBRARY)
-- Jsoncpp header: /yocto_projects/partitions/9/poky/build/tmp/sysroots/socfpga_cyclone5/usr/include
-- Jsoncpp lib   : JSONCPP_LIBRARY-NOTFOUND
-- Jsoncpp prefix: json
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Threads:
-- Could NOT find argtable (missing:  ARGTABLE_INCLUDE_DIR ARGTABLE_LIBRARY)
-- Argtable header: ARGTABLE_INCLUDE_DIR-NOTFOUND
-- Argtable lib   : ARGTABLE_LIBRARY-NOTFOUND
CMake Error at /yocto_projects/partitions/9/poky/build/tmp/sysroots/i686-linux/usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CURL (missing: CURL_INCLUDE_DIR CURL_LIBRARY)
Call Stack (most recent call first):
  /yocto_projects/partitions/9/poky/build/tmp/sysroots/i686-linux/usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCURL.cmake:46 (find_package_handle_standard_args)
  cmake/CMakeDependencies.cmake:31 (find_package)
  CMakeLists.txt:53 (include)


-- Configuring incomplete, errors occurred!
See also "/yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/build/CMakeFiles/CMakeOutput.log".
See also "/yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/build/CMakeFiles/CMakeError.log".
WARNING: /yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/temp/run.do_configure.18925:1 exit 1 from
  cmake ${OECMAKE_SITEFILE} /yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/git -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_BINDIR:PATH=/usr/bin -DCMAKE_INSTALL_SBINDIR:PATH=/usr/sbin -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/lib/libjson-rpc -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=/com -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib -DCMAKE_INSTALL_INCLUDEDIR:PATH=/usr/include -DCMAKE_INSTALL_DATAROOTDIR:PATH=/usr/share -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_TOOLCHAIN_FILE=/yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/toolchain.cmake -DCMAKE_VERBOSE_MAKEFILE=1 ${EXTRA_OECMAKE} -Wno-dev
ERROR: Function failed: do_configure (log file is located at /yocto_projects/partitions/9/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/libjson-rpc/git-r0/temp/log.do_configure.18925)
                                                                             21,1          Bas

**Comment by loreilei** [comment]
Well it depends on what you want to compile : either you add dependencies (argtable, curl, jsoncpp, libmicrohttpd...) or you overload do_configure() to set some varaible to NO (as you would do from command line).

For instance, if you want to use only tcp connectors, you might not need http connector, unix domain socket conenctors, or stub generators ?

**Comment by Nouri1111** [comment]
I will nedd for Http because I use the httpserver and httpclient demo, so hwo I can add the dependencies

**Comment by Nouri1111** [comment]
I will need for Http because I use the httpserver and httpclient demo, so hwo I can add the dependencies

**Comment by loreilei** [comment]
Just had a variable "DEPENDS" like this : 
DEPENDS="<library name 1> <library name 2> ... <library name N>"

**Comment by cinemast** [comment]
@loreilei of course. I am not that much familiar with yocto. Than a pull-request which alters the README to explain how to use libjson-rpc-cpp inside the yocto project is also fine. Just like I did for Arch Linux.

**Comment by Nouri1111** [comment]
So the depends will be: 
DEPENDS += "libcurl4-openssl-dev libjsoncpp-dev libargtable2-dev libboost-test-dev"
It's correct!!

**Comment by Nouri1111** [comment]
Could you please tell me what is the right way for write depends 
libcurl4-openssl-dev libjsoncpp-dev libargtable2-dev libboost-test-dev

how to write : DEPENDS += "......."

**Comment by loreilei** [comment]
Values in DEPENDS and RDEPENDS are recipe names.

**Comment by Nouri1111** [comment]
Could you please tell me what I should put in DEPENDS and in RDEPENDS ?

**Comment by cinemast** [comment]
@Nouri1111 how are you doing with this? Can we close this issue?

**Comment by cinemast** [comment]
Close due to inactivity of the reporter
