### ISSUE TITLE
How I can add argtable2 to DEPENDS ="..."  for cross compilation , does it exist!!

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#124]

**Comment by loreilei** [comment]
According to http://layers.openembedded.org/layerindex/branch/master/recipes/?q=argtable

recipe for argtable does not exist yet. Guess you should write it too. BTW argtable is only required for stub generators (@cinemast coorect this statement if i'm wrong).

**Comment by Nouri1111** [comment]
Thanks for your replay 
So how to deactivate this option to cross compile the libjson-rpc!!

**Comment by cinemast** [comment]
@loreilei: exactly. argtable2 is only required for the stub generator. So you can use the stub-generator on a non embedded platform to generate the stub code.

@Nouri1111: It is described in the README: https://github.com/cinemast/libjson-rpc-cpp#build

```
mkdir build
cd build
cmake -DCOMPILE_STUBGEN=NO -DCOMPILE_EXAPMLES=NO ..
make
```

This will build libjson-rpc-cpp without requiring libargtable2.

Also I'd like to mention that this issues is related to #123. So please keep the conversation to #123. Also I think it is a bit out of scope here, but if @loreilei is happy to help you out, you are lucky :)

**Comment by cinemast** [comment]
Additionally. Please do not post the whole question into the title. Rather use the description field for this. Thank you :)
