### ISSUE TITLE
Could NOT find Git (missing:  GIT_EXECUTABLE)

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#126]
Hello 
When I try cross compile the libjson-rpc with yocto the below message displayed:
Could NOT find Git (missing:  GIT_EXECUTABLE)

Could you please tell me how to desactivate or to add the GIT recipe
thanks in advance

**Comment by cinemast** [comment]
You could disable the test suite (which requires git, to fetch the CATCH unit testing library).

```
cmake -DCOMPILE_TESTS=NO ..
make
```

**Comment by Nouri1111** [comment]
thanks for you replay but I compile with yocto so I m looking for script to disable GIT, DOXYGEN CATCH..
Thanks in advance

**Comment by loreilei** [comment]
Hi !

I don't think you'll find such scripts here... A simple way to get rid of those messages would be to install git and doxygen on your host.

Another way to do it is to add a native dependency to your recipe. I guess recipe name "git-native" would go well for git. Such a dependency will build git for the host and not for the target which will get you rid of those messages.

**Comment by Nouri1111** [comment]
I added to my file .bb : BBCLASSEXTEND = "native"
but I have always git doxygen, catch problems
Could NOT find Git (missing: GIT_EXECUTABLE)
Could NOT find Git (missing: DOXYGEN_EXECUTABLE)
Could NOT find Git (missing: CATCH_EXECUTABLE)

Is there other way to desactivate these libs

**Comment by loreilei** [comment]
Doing that only allows your recipe to be compiled for native host. You need to add "git-native" recipe to your recipe  dependencies or install git on your host.

I'm just wondeting: are you new with yocto/openembedded ?

**Comment by Nouri1111** [comment]
Yes I'm new and I don't know how to add "git-native" recipe
Could you tell me please
thanks in advance

**Comment by Nouri1111** [comment]
using this command I got the same error :
DEPENDS = " git-native"

**Comment by loreilei** [comment]
Hmm weird, git inherits native class in its recipe...

Did you try to disable tests like cinemast said ?

Either you overload do_configure() in your recipe or modifiy EXTRA_OECONF variable to do so.

EXTRA_OECONF += "-DCOMPILE_TESTS=NO" for instance ? (can't ensure it will work, I'm poiting this out of memory and has nothing to try it now).

**Comment by Nouri1111** [comment]
I added: 
EXTRA_OECMAKE   += "-DCOMPILE_TESTS=NO"
EXTRA_OECMAKE   += "-DCOMPILE_STUBGEN=NO"
EXTRA_OECMAKE   += "-DCOMPILE_EXAMPLES=NO"

Always I have the same error
 Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
| -- Could NOT find catch (missing:  CATCH_INCLUDE_DIR)
| Could not find catch, downloading it now
| CMake Error at /share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:107 (message):
|   Could NOT find Git (missing: GIT_EXECUTABLE)
| Call Stack (most recent call first):
|   /Modules/FindPackageHandleStandardArgs.cmake:314 (_FPHSA_FAILURE_MESSAGE)
|   /Modules/FindGit.cmake:61 (find_package_handle_standard_args)
|   src/catch/CMakeLists.txt:4 (find_package)

Is there other idea!!

**Comment by loreilei** [comment]
Disable documentation generation ?

Also you can write 
EXTRA_OECMAKE += "-DCOMPILE_TESTS=NO"
EXTRA_OECMAKE += "-DCOMPILE_STUBGEN=NO"
EXTRA_OECMAKE += "-DCOMPILE_EXAMPLES=NO"
as
EXTRA_OECMAKE += "-DCOMPILE_TESTS=NO \
                                      -DCOMPILE_STUBGEN=NO \
                                      -DCOMPILE_EXAMPLES=NO"

**Comment by Nouri1111** [comment]
I got the same error even with: 
EXTRA_OECMAKE += "-DCOMPILE_TESTS=NO \
-DCOMPILE_STUBGEN=NO \
-DCOMPILE_EXAMPLES=NO"
I think I  have to cross compile a recipe for catch

**Comment by cinemast** [comment]
Same topic as #127
