### ISSUE TITLE
cross compile libjson-rpc with yocto

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#127]
Hello, 
when I tried to compile libjson-rpc with yotco I got the below error:
 -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
| -- Could NOT find catch (missing:  CATCH_INCLUDE_DIR)
| Could not find catch, downloading it now
| CMake Error at /share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:107 (message):
|   Could NOT find Git (missing: GIT_EXECUTABLE)
| Call Stack (most recent call first):
|   /Modules/FindPackageHandleStandardArgs.cmake:314 (_FPHSA_FAILURE_MESSAGE)
|   /Modules/FindGit.cmake:61 (find_package_handle_standard_args)
|   src/catch/CMakeLists.txt:4 (find_package)

Could yoy please tell me how to solve this problem

**Comment by cinemast** [comment]
I am in no way familiar with yocto, but the error already says: Doxygen and Catch is missing from your system. They are both not really required by the framework. You can turn off tests and if doxygen is not found, the doc target is simply not available. So I think this is something yocto specific.

**Comment by cinemast** [comment]
Also you already opened 2 other issues #126  and #123. They are all about the same problem. Please stick to 1 thread.

**Comment by nefethael** [comment]
For the record, magic trick should be:

inherit cmake
OECMAKE_FIND_ROOT_PATH_MODE_PROGRAM = "BOTH"
