### ISSUE TITLE
Compiling examples on windows 7

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#128]
Hello I tried to compile server and client examples on wondows I added the \include to the path 
but I get always compile error:
C:\json-rpc>g++ server.cpp
server.cpp:30:53: fatal error: jsonrpccpp/server/connectors/httpserver.h: No suc
h file or directory
 #include <jsonrpccpp/server/connectors/httpserver.h>

Could you please tell me how to inculde header files in windows 
a tried 
#include <jsonrpccpp/server/connectors/httpserver.h>
//#include <jsonrpccpp\server\connectors\httpserver.h>
Always I had yhe same error
thanks in advance
                                                     ^

**Comment by loreilei** [comment]
Add a -I option to show g++ where libjsoncpp is. You might also need to add a -L option to succesfully link.

**Comment by Nouri1111** [comment]
I use the command:
g++ server.cpp -ljsoncpp -lmicrohttpd -ljsonrpccpp-common -ljsonrpccpp-server -o sampleserver
 
and I got always the same error:

C:\json-rpc>g++ server.cpp -ljsoncpp -lmicrohttpd -ljson
rpccpp-common -ljsonrpccpp-server -o sampleserver
server.cpp:30:53: fatal error: jsonrpccpp/server/connectors/httpserver.h: No suc
h file or directory
 #include <jsonrpccpp/server/connectors/httpserver.h>
                                                     ^
I think the problem is about the path,!!

**Comment by loreilei** [comment]
Yeah that's why I told you to add a -I option (btw that's an uppercase i, not a lowercase L).

**Comment by Nouri1111** [comment]
-l or -L used for link not for include files
so the  problem is before using -l or -L

**Comment by loreilei** [comment]
If you provide a -I <some path> (uppercase i), it tells g++ to look in this path to for the files included with #include <>.

**Comment by Nouri1111** [comment]
ok Thanks 
so where I should add the -l 
g++ server.cpp -ljsoncpp -lmicrohttpd -ljsonrpccpp-common -ljsonrpccpp-server -o sampleserver

and I got always the same error:
and which line I should use 
#include <jsonrpccpp/server/connectors/httpserver.h>
Or
#include <jsonrpccpp\server\connectors\httpserver.h>

Thanks in advance

**Comment by Nouri1111** [comment]
It s work with addind -I option
