### ISSUE TITLE
libcurl error: 6

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#129]
Hello, 
I compiled the server and the client and when I tried to start the client I get the below error
Could you please help me, thanks in advance 
 ./client 
Exception -32003 : Client connector error: libcurl error: 6

**Comment by cinemast** [comment]
http://curl.haxx.se/libcurl/c/libcurl-errors.html

There is a list of error code explanations. Apparently the host you are trying to connect is not reachable.
