### ISSUE TITLE
How to connect with json-rpc using2 PCs

### ISSUE THREAD

**Issue by Nouri1111** [cinemast/libjson-rpc-cpp#130]
Hello,
I want to connect client(windows) ans server(linux) using json rpc
Could you please with code I have to change on server side !
is this syntax correct: jsonrpc::HttpClient clRpcClient("http//192.168.10.3:8383");
thanks in advace

**Comment by loreilei** [comment]
Typo in your URL ? 
From "http//192.168.10.3:8383" to "http://192.168.10.3:8383" ?
