### ISSUE TITLE
Call method without parameters

### ISSUE THREAD

**Issue by BuilovAlexey** [cinemast/libjson-rpc-cpp#134]
I want call method from server
```
        [JsonRpcMethod] 
        public string GetWindowsUserName()
        {
            return System.Environment.UserName;
        }
```

I use https://github.com/Astn/JSON-RPC.NET framework for server.

In client i need call method without parameters:
```
        Json::Value params;
        params = Json::Value::null;
        Value methodResult = clientNew.CallMethod("GetWindowsUserName", params);
```

but i get 
```Exception -32602 : INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised: Invalid params, data: "The number of parameters could not be counted"```
With use "params = Json::nullValue" i get same result.
 How i can to call method without parameters?

P.s. when i call method with parameters I get normal result.

**Comment by cinemast** [comment]
Sounds to me like an error on the side of JSON-RPC.NET. If there are no parameters passed, the params field can be ommited. It is also in the JSON-RPC specification: http://www.jsonrpc.org/specification

You should raise an issue at JSON-RPC.NEt about this.

**Comment by BuilovAlexey** [comment]
ok, but if server will by libjson-rpc-cpp server, what i must to do, to call method without parameters?
Will my example work? or what value must have "params", if method "GetWindowsUserName" haven't parameters?
```   
  Json::Value params;
  params = Json::Value::null;
  Value methodResult = clientNew.CallMethod("GetWindowsUserName", params);
```

**Comment by BuilovAlexey** [comment]
A try call method without parameters:
```
	Json::Value params;
	params = Json::Value::null;
	HttpClient httpClient("http://localhost:3333/");
	Client clientNew(httpClient);
	Value methodResult = clientNew.CallMethod("GetWindowsUserName", params);
```

In server i get this request message: {"id":1,"jsonrpc":"2.0","method":"GetWindowUserName"}

i find here http://support.mashery.com/docs/read/mashery_api/20/JSON_RPC example without parameters. in this case json request:
```{
    "jsonrpc": "2.0",
    "method": "test.hello",
    "params": [],
    "id": 1
}```

**Comment by cinemast** [comment]
Yes, it is an error in the JSON-RPC.NET framework. You really should raise an issue there with your findings and reference this issue here.

**Comment by BuilovAlexey** [comment]
JSON-RPC.NET last commit was half year ago.. and author don't answer to users by last some issues. okey may be i will raise issue, but i haven't time for wait bug fix.

**Comment by BuilovAlexey** [comment]
omg... they fix this bug in one of the last commits, but don't refresh nuget package...

**Comment by BuilovAlexey** [comment]
omg... they fix this bug in one of the last commits, but don't refresh nuget package...
