### ISSUE TITLE
Compiling error when building from source

### ISSUE THREAD

**Issue by njaliu** [cinemast/libjson-rpc-cpp#135]
I am trying to build the framework from source. When following the instructions with the command "cmake .. && make" and compiling it, errors are reported as follows:

Scanning dependencies of target jsonrpcstub
[ 61%] Building CXX object src/stubgenerator/CMakeFiles/jsonrpcstub.dir/main.cpp.o
Linking CXX executable ../../bin/jsonrpcstub
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Value::toStyledString() const'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Value::isMember(std::string const&) const'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::StyledWriter::write(Json::Value const&)'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Value::getMemberNames() const'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Value::operator[](std::string const&)'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Value::operator[](std::string const&) const'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Value::Value(std::string const&)'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Reader::parse(std::string const&, Json::Value&, bool)'
../../lib/libjsonrpccpp-common.so.0.6.0: undefined reference to `Json::Value::asString() const'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/jsonrpcstub] Error 1
make[1]: *** [src/stubgenerator/CMakeFiles/jsonrpcstub.dir/all] Error 2
make: *** [all] Error 2

I am using Ubuntu 14.04. Any insights would be appreciated here, thanks :)

**Comment by cinemast** [comment]
Which compiler version are you using?

**Comment by njaliu** [comment]
I am using GCC 4.8.4

**Comment by cinemast** [comment]
Are you definitely sure Cmake is not using GCC > 5.x? Because thit would explain a lot.

**Comment by cinemast** [comment]
See here: https://github.com/cinemast/libjson-rpc-cpp/issues/131

**Comment by njaliu** [comment]
Thanks for connecting me to the previous issue. But I do not have a 5.x GCC in the system. I list all the compilers and only see gcc 4.8.4 and g++ 4.8.4. Any other possibilities? This really kills me...

**Comment by loreilei** [comment]
Hi!

Since it's a linker error, are you sure that cmake find the right json library ? Or that it is installed on your os ?

**Comment by njaliu** [comment]
Hi, I'm not familiar with this, but I installed the libjsoncpp following the instruction. Based on the error messages, this should be related to the json library. How can I determine whether the library is correctly used? Or could it be due to the incompatible cmake version? thanks!

**Comment by cinemast** [comment]
I currently don't happen to have a 14.04 image here, just a 12.04. I will try to reproduce your issue.

**Comment by cinemast** [comment]
I cannot reproduce this issue, is it still a problem?
