### ISSUE TITLE
build failed on fedora 22 , if enable COMPILE TEST

### ISSUE THREAD

**Issue by smartbitcoin** [cinemast/libjson-rpc-cpp#136]
build failed on fedora 22 , if enable COMPILE TEST

**Comment by cinemast** [comment]
Can you please provide a build log?

**Comment by cinemast** [comment]
Since there is no response I guess you fixed the problem?

**Comment by loreilei** [comment]
Hi @cinemast, I am a bit busy those days but I quickly checked the log.

The errors I saw were on system call parameters. I saw them while I was writing the code but I am not sure those are fixable since it's system calls.
