### ISSUE TITLE
Bi-directional JSON-RPC communication over HTTP

### ISSUE THREAD

**Issue by alt1972** [cinemast/libjson-rpc-cpp#138]
Hello,

it's implemented some bidirectional communication (for instance long polling) in order to allow the server push messages to the client.

I think JSON-RPC 1.0 specs support that behaviour. ( To give the serverside peer a chance to send messages to the client side peer, the client side peer may reopen communication by sending an empty HTTP POST)
Regards,

**Comment by cinemast** [comment]
Hi!

It is currently not directly supported. What you can do is host on each peer a JSON-RPC Server and Client. This way they can communicate in both directions.

**Comment by alt1972** [comment]
hello.
It's a pitty :-(
The solution that you say is not good using devices connetced to, for instance, "3G network" where is not allowed entry connections (when you have a server on the client side)

**Comment by loreilei** [comment]
Hi !

It might not be the best solution, but have you considered the client to poll the server for messages ?

Like a method the client calls and the server answer with client's message ?
