### ISSUE TITLE
libjson can't accept "id" members over 2147483647

### ISSUE THREAD

**Issue by EricLagergren** [cinemast/libjson-rpc-cpp#141]
libjson-rpc calls [`Json::Value::isInt`](https://github.com/cinemast/libjson-rpc-cpp/blob/8dc16d351ce9a46fedc82c5f60874751db30fef2/src/jsonrpccpp/server/rpcprotocolserverv2.cpp#L80) which has an upper bound of 2147483647 ((2^32 - 1) / 2).

Unfortunately, some JSON-RPC clients use up to [2^63 - 1](https://github.com/gorilla/rpc/blob/master/v2/json2/client.go#L47) which means libjson-rpc returns an error message.

IMO, it'd be beneficial to change this to [`Json::Value::isUInt64`](https://github.com/open-source-parsers/jsoncpp/blob/34bdbb58b4b0c02eb054b45be46fa33cff450e19/src/lib_json/json_value.cpp#L1269) since 2147483647 is only half of a max Uint32.

I could submit a PR if you'd like.

**Comment by cinemast** [comment]
yes, please.

**Comment by EricLagergren** [comment]
Urgh. The Travis CI build is breaking because its version of libjson [doesn't have `Json::Value::isUInt64](https://travis-ci.org/cinemast/libjson-rpc-cpp/builds/93727949#L1450) for whatever reason.

My local tests passed, and libjson's `Json::Value` *does* have `isUInt64`...

**Comment by EricLagergren** [comment]
I'll submit a fix for [this failure](https://travis-ci.org/cinemast/libjson-rpc-cpp/builds/93729196#L1938) when I get back home tonight (I'm PST).

**Comment by cinemast** [comment]
Hi @EricLagergren!

Would you still be able to supply a fix for this? We cannot loose 32bit support.

**Comment by EricLagergren** [comment]
@cinemast [The most recent Travis CI test passed](https://travis-ci.org/cinemast/libjson-rpc-cpp/builds/93754570) and afaik `isIntegral` will not break 32 bit support.

The `isIntegral` method [seems to have both 32- and 64-bit support](https://github.com/open-source-parsers/jsoncpp/blob/34bdbb58b4b0c02eb054b45be46fa33cff450e19/src/lib_json/json_value.cpp#L1289)
