### ISSUE TITLE
Duplicates handling - configuration of the Json::Reader class

### ISSUE THREAD

**Issue by vinc999** [cinemast/libjson-rpc-cpp#144]
I have a problem with duplicates in json objects. Not sure if this is against the json/jsonrpc specification, however whenever you pass json objects with duplicated fields - no error is returned. 
I am looking for an option to configure parser so it returns error while duplicated entries are found.

As I understand it sits deep in the jsoncpp lib, where everything is done in the Reader class which Features object to specify how it reacts to certain situations. Also jsoncpp lib provides OurReader class with OurFeatures that include duplicate handling code (I did not read the whole libjsoncpp code, so I am not sure If we are supposed to used these two) .

Is it possible to use OurReader instead of Reader in libjson-rpc-cpp and access to OurFeatures class to the user so it is possible to configure json parser to meet specific needs ?

**Comment by cinemast** [comment]
It is not possible yet, no. I will give it a look.

**Comment by cinemast** [comment]
Hi!

Referring to this: http://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object

The JSON standard does not actually forbid such situations. Therefore neither does the json-rpc standard.

Therefore I'd like to keep things as they are.
