### ISSUE TITLE
Error on Windows 10

### ISSUE THREAD

**Issue by preraksola** [cinemast/libjson-rpc-cpp#145]
Hello,
As stated in the **README** file, I downloaded the exe for setting up this library on Windows 10 64-bit.
The installation went smooth and when I tried to execute `jsonrpcstub` on `spec.json` file, it said following two dlls are missing.
1. libgcc_s_dw2-1.dll
2. libstdc++-6.dll

So, I added them in the `C:\Program Files (x86)\libjson-rpc-cpp 0.5.0\bin` folder and tried again to run the command.

And this time, it throws an error saying 
`The application failed to start properly (0xc0000142).
Click OK to close the application`

Can you please let me know, how can I solve this thing to successfully generate the stub files?

Thank you,
Prerak

**Comment by cinemast** [comment]
Hi!

Probably the libraries are of the wrong version. I haven't tested it under Windows 10. The latest working version I used was Windows 7. I used gcc 4.8 to compile the binaries. Alternatives would be to compile the framework on your own, or use a linux machine to generate the stub files.

I currently don't have the resources to support Windows equally to Linux. If you come up with a solution that works, It would be great if you could post them here.

Greetings
Peter

**Comment by preraksola** [comment]
Hi,
I tried to compile the library on my own too, but its giving me errors in the first step itself (`cmake .. && make`)!
I have attached the log file of cmake.
Can you please have a look at it and let me know, what can I do?

Prerak



[CMakeError.txt](https://github.com/cinemast/libjson-rpc-cpp/files/58102/CMakeError.txt)
[CMakeOutput.txt](https://github.com/cinemast/libjson-rpc-cpp/files/58103/CMakeOutput.txt)

**Comment by cinemast** [comment]
I am sorry I currently do not have access to a Windows 10 installation. The problem I see from your logs is that you used the Visual Studio generator instead of the Mingw. The code is not supported by Visual Studio at the moment.

**Comment by yuhasem** [comment]
I was having the same problem on my Windows 10 installation. It looks like Visual Studio does not ship with the problem causing dll's, so I installed gcc and g++ through MinGW, making sure that the dll's were added to the PATH environment variables and I was able to proceed with stub generation.

**Comment by cinemast** [comment]
Thank you @yuhasem. Visual Studio is not officially supported by this framework. Please use the GNU toolchain.
