### ISSUE TITLE
Compatibility with SOCKS5

### ISSUE THREAD

**Issue by Jesse-V** [cinemast/libjson-rpc-cpp#147]
This library should support SOCKS5 or other connection proxies, since communication doesn't always occur directly. I'm also interested in knowing how to workaround this issue so that users of my application can use this library with a SOCKS5 proxy.

**Comment by cinemast** [comment]
Hi Jesse!

Are you talking about Client support? If yes, your operating system can deal with SOCKS proxies for outgoing connections.

I have currently no interest in adding SOCKS support to this framework. Anyway you are very welcome to contribute new connectors to this project and I will review and merge them if appropriate.

**Comment by cinemast** [comment]
This would be a good starting point: http://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by Jesse-V** [comment]
@cinemast Thanks for getting back to me so quickly, and thanks for the link. Yes, I would like my users to use SOCKS5. This is part of an application for the Tor network: clients build connections to their SOCKS5 proxy on localhost, which then carries the packets through the network to the server at the other end. It's technically impossible to connect to the server directly.

Is HTTP the only transport you currently support, or do you support raw TCP connection? I don't quite understand yet how you have organized your software or how you use Curl. Clearly Curl supports SOCKS5, so I guess that if I can get down to the raw Curl level, rather than HTTP, I'd have a much better chance of being able to use SOCKS5.

**Comment by cinemast** [comment]
What you do sounds interesting, maybe I will give it a look myself. Do you have further references to your project?

Actually the connectors are very well split out in the architecture. Here is the HTTP Client code which uses CURL.

https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/client/connectors/httpclient.cpp

There is a raw TCP socket implementation on the dev branch, but I don't recommend using it since its third party contributed and I haven't reviewed it yet properly. Anyway using the additional CURL options is easier anyway.

**Comment by Jesse-V** [comment]
@cinemast Certainly. https://github.com/Jesse-V/OnioNS-client is the client-end. There are actually four OnioNS-* repositories. I am attempting to transition from Boost Asio (which is a ~100 MB dependency) to your library, which is comparatively tiny and looks promising so far. I need to solve this SOCKS5 issue and then I need to ensure that the server is asynchronous.

Oh, nice, thanks for the code. That seems easy enough to mess with. Thanks!

**Comment by Jesse-V** [comment]
@cinemast I just added SOCKS5 support in [this commit](https://github.com/Jesse-V/libjson-rpc-cpp/commit/bade39bf592b8c184a8c1ae193ef64d9919d16fb). It's rough, but it does seem to work. I can reach a remote server through Tor! Hopefully I'll have time to clean it up, add unit tests, and submit a pull request to you.

Now that I've had a chance to examine your code, I see that it's actually fairly organized and clear. I'd like to remove the HTTP transport and just have JSON-RPC over raw TCP client/server, but that's my next task and outside the scope of this repo. I'll close off this ticket. Thanks again for the help.

**Comment by Jesse-V** [comment]
@cinemast I've made some good progress incorporating my fork into my project. However, for some reason, my Socks5Client.cpp file is not being compiled when I build your project, so it's not included in any of the .so library files. Your CMake-Fu is better than mine and I have been unable to find where you specify all of the .cpp files, so I don't know how to add mine. I had this working a while ago, but for some reason it simply isn't compiling my file anymore. What do you suggest?

**Comment by cinemast** [comment]
Hi!

The connectors are handled conditionally. See for example in the HTTPClient connector: https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/CMakeLists.txt#L36

**Comment by Jesse-V** [comment]
@cinemast thanks. I found that within a few minutes of posting my comment. I thought I'd delete the comment to avoid wasting your time, but you must have received the notification anyway. :)
