### ISSUE TITLE
compilation problem - missing catch.hpp

### ISSUE THREAD

**Issue by marcoben73** [cinemast/libjson-rpc-cpp#148]
I've tried to build the library but I got the following error

[ 76%] Building CXX object src/test/CMakeFiles/unit_testsuite.dir/test_common.cpp.o
/home/marco/software/libjson-rpc-cpp/src/test/test_common.cpp:10:21: fatal error: catch.hpp: No such file or directory
 #include <catch.hpp>

My environment
Linux 3.19.8-100.fc20.x86_64 (Fedora 20)
cmake version 2.8.12.2
g++ (GCC) 4.8.3 20140911 (Red Hat 4.8.3-7)

**Comment by cinemast** [comment]
Do you have internet connection on your machine? Usually the catch library gets downloaded automatically via cmake. 

Otherwise Fedora provides the catch library as a package:
https://admin.fedoraproject.org/pkgdb/package/rpms/catch/

**Comment by marcoben73** [comment]
I've internet connection.
I checked in the build directory and the catch package has been downloaded and compiled.
It seems that the problem is in the cmake or makefile that doesn't set the correct path for include files, but I didn't find exacltly where the problem is.

**Comment by cinemast** [comment]
I will check on that.

**Comment by marcoben73** [comment]
A workaround is to disable the build of tests
cmake -DCOMPILE_TESTS=NO
So make finishes without errors and it's possible to install the library

**Comment by Jesse-V** [comment]
It's not a good idea to download/clone software during the compile step. That's generally discouraged by most Linux distributions and will cause your library to fail on build systems that may not have an Internet connection, which will be true for any security-enhanced build system such as Fedora's. Is there any way that you could declare the library as a dependency?

**Comment by Jesse-V** [comment]
Catch still seems to be referenced in another file, so simply disabling COMPILE_TESTS doesn't remove the dependency. The actual workaround is "-DCOMPILE_TESTS=NO -DCATCH_INCLUDE_DIR=/dev/null"

**Comment by cinemast** [comment]
Hi!

Usually, the package is not downloaded, if the Catch header is already found on the system. I use this behaviour also in the Debian package: http://anonscm.debian.org/cgit/collab-maint/libjson-rpc-cpp.git/tree/debian

I will fix the issue about downloading, even if COMPILE_TESTS is NO. Thanks for mentioning that.

**Comment by giacecco** [comment]
Hi @cimenast, in case you did not think about it, release 0.6.0 precedes when you fixed this, so the issue is still there for the ones who - like me - started from downloading 0.6.0 expecting it to be more stable. Perhaps it's worth releasing a 0.6.1 or something? Thanks!

**Comment by cinemast** [comment]
Hi!

I am planning to prepare a release soon. There are still some changes I need to test.

Greetings
