### ISSUE TITLE
Double free on HttpClient destroy

### ISSUE THREAD

**Issue by turgo** [cinemast/libjson-rpc-cpp#149]
When I destroy an object having a pair of jsonrpc::HttpClient and jsonrpc::Client members, I get a "double free or corruption" error. The initialization is the following:

```
Server::Server(const string &url) : mHttpClient(url), mClient(mHttpClient)
{
}
```

The runtime error:
```
double free or corruption (!prev): 0x00000000015cc050 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7283f)[0x7fdb4b94083f]
/lib64/libc.so.6(+0x780ae)[0x7fdb4b9460ae]
/lib64/libc.so.6(+0x78db6)[0x7fdb4b946db6]
/usr/lib64/libcurl.so.4(+0x1e49e)[0x7fdb4b67849e]
/usr/lib64/libcurl.so.4(curl_easy_cleanup+0x2a)[0x7fdb4b6881ea]
/usr/local/lib/libjsonrpccpp-client.so.0(_ZN7jsonrpc10HttpClientD1Ev+0x2e)[0x7fdb4d0d2450]
```

Please help me to solve this. Thanks in advance!

**Comment by cinemast** [comment]
I need more context to help you out here. I don't see any memor allocations or frees here. Please provide more code.

Greetings

**Comment by turgo** [comment]
It was in my code, sorry for disturbing You! I passed my Server object by reference to an other constructor, but copied it into a variable there (an & was missing in that variable declaration). Thanks for the support!
