### ISSUE TITLE
test connector_http fails

### ISSUE THREAD

**Issue by iperry** [cinemast/libjson-rpc-cpp#152]
It looks like somebody has registered someinvalidurl:

```
zsh▸ dig someinvalidurl

; <<>> DiG 9.10.3-P3 <<>> someinvalidurl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 62026
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;someinvalidurl.			IN	A

;; AUTHORITY SECTION:
.			1271	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2016021701 1800 900 604800 86400

;; Query time: 16 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Wed Feb 17 19:23:41 EST 2016
;; MSG SIZE  rcvd: 118
```

This makes the connector_http fail, since http://someinvalidurl/asdf is actually... valid.

**Comment by cinemast** [comment]
Hi!

I cannot reproduce this. Are you sure its nothing on your local network thats causing to let someinvalidurl exist?

**Comment by iperry** [comment]
Pretty sure. My local network forwards DNS queries to Google's public DNS:
```
dig @8.8.8.8 someinvalidurl

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> @8.8.8.8 someinvalidurl
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 52931
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;someinvalidurl.			IN	A

;; AUTHORITY SECTION:
.			1692	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2016021800 1800 900 604800 86400

;; Query time: 17 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Feb 18 10:16:05 UTC 2016
;; MSG SIZE  rcvd: 118
```
I performed this query from three different sites and two different nameservers (Linode DNS and Google DNS).

FWIW, I changed the URL in the test to jibberish and the test passed for me.

**Comment by iperry** [comment]
Nevermind, I totally misread the answer section. This must be something weird on my local network. I'll take a look. thanks.

**Comment by iperry** [comment]
In case you were wondering, the local DHCP server was handing out a domain name which had a wildcard record registered by our hosting provider.

**Comment by cinemast** [comment]
Glad you got it fixed :)
