### ISSUE TITLE
Error compile libjson-rpc-cpp yocto

### ISSUE THREAD

**Issue by tanml** [cinemast/libjson-rpc-cpp#155]
Dear all,

I am encountering the issue as below, can you please help me on this?

CMake Error at src/jsonrpccpp/CMakeLists.txt:163 (install):
|   install TARGETS given unknown argument "/lib".
| 
| 
| -- Configuring incomplete, errors occurred!
| See also "/home/lia1hc/projects/bosch-poky/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/libjson-rpc-cpp/0.2-r1/build/CMakeFiles/CMakeOutput.log".
| See also "/home/lia1hc/projects/bosch-poky/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/libjson-rpc-cpp/0.2-r1/build/CMakeFiles/CMakeError.log".
| WARNING: exit code 1 from a shell command.

**Comment by cinemast** [comment]
Sorry I do not have any experience in yocto. Beside that I do not offer free support to commercial companies.
