### ISSUE TITLE
Windows binary package compatible with current MinGW (GCC 5.3+)

### ISSUE THREAD

**Issue by slomkowski** [cinemast/libjson-rpc-cpp#158]
When I try to link my code with libjson-rpc-cpp, I get the following error:

```
undefined reference to `jsonrpc::HttpServer::HttpServer(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
```

I assume that it because I use MinGW with GCC 5.3.0 and libjson-rpc-cpp binary distribution (version 0.5.0) was compiled against GCC 4.x. I tried to compile it myself, but I ran into dependency hell. Is current MinGW going to be supported in near future and appropriate binary packages provided?

**Comment by cinemast** [comment]
Hi, yes this is exactly the problem. Well I have to state here that Windows is not the primary target platform for this framework. I will try to recompile it for windows with GCC 5+.

**Comment by slomkowski** [comment]
@cinemast any progress?

**Comment by cinemast** [comment]
Sorry, I currently do not find the time.

**Comment by slomkowski** [comment]
I managed to compile it using flag `-D_GLIBCXX_USE_CXX11_ABI=0`. The executables run after I copied all DLL-s from *libjson-rpc-cpp_win32-deps.zip* and base libs such as libstdc++ from GCC 4.x installation. This strange mix seems to run demo programs, but they fail to communicate and throw exceptions as well.

BTW I was playing with this instead of simply installing older MinGW with GCC 4.x, because I use Arch Linux as my development environment and cannot find older packages.

**Comment by cinemast** [comment]
Ah I see, so you are actually cross-compiling. I never found a good tutorial for cmake doing that.

**Comment by slomkowski** [comment]
I managed to have it working. I created package which follows convention for other MinGW libraries. If anyone interested: https://github.com/slomkowski/PKGBUILDs/tree/master/mingw-w64-libjson-rpc-cpp

**Comment by cinemast** [comment]
Thank you for sharing.

**Comment by slomkowski** [comment]
@cinemast I just noticed that you are the maintainer of the original Arch package. Are you willing to take over PKGBUILD I've created and send it to AUR/maintain it?
