### ISSUE TITLE
Package not available for Debian

### ISSUE THREAD

**Issue by capnslipp** [cinemast/libjson-rpc-cpp#159]
On the latest Debian version (8.4 / Jessie):

~~~
 ➜ sudo apt-get install libjsonrpccpp-dev libjsonrpccpp-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libjsonrpccpp-dev
E: Unable to locate package libjsonrpccpp-tools
~~~

Likewise, searching the Debian package search website for Jessie packages with “libjsonrpc” in the package name returns no results ([packages.debian.org/search?keywords=libjsonrpc&searchon=names&suite=jessie&section=all](https://packages.debian.org/search?keywords=libjsonrpc&searchon=names&suite=jessie&section=all)).

**Comment by cinemast** [comment]
Hi!

I should probably clarify that it is only available in current debian testing.

Here is the link: https://packages.debian.org/source/stretch/libjson-rpc-cpp

Greetings

**Comment by capnslipp** [comment]
So then my only option is to build from source, right?  There aren't any backports you know of?

**Comment by cinemast** [comment]
None that I maintain or am aware of, but since Ubuntu is basically importing packages from Debian, all dependencies are available in Debian.

This should allow you to install the Ubuntu packages from Wily (15.10) right away. You can download theme here:

http://packages.ubuntu.com/source/wily/libjson-rpc-cpp

Download the following debs and install them in this order:

libjsonrpccpp-common0
libjsonrpccpp-client0
libjsonrpccpp-server0
libjsonrpccpp-stub0
libjsonrpccpp-tools
libjsonrpccpp-dev

**Comment by capnslipp** [comment]
~~~
 ➜ sudo dpkg --install libjsonrpccpp-common0_0.6.0-2_amd64.deb
Selecting previously unselected package libjsonrpccpp-common0.
(Reading database ... 59491 files and directories currently installed.)
Preparing to unpack libjsonrpccpp-common0_0.6.0-2_amd64.deb ...
Unpacking libjsonrpccpp-common0 (0.6.0-2) ...
dpkg: dependency problems prevent configuration of libjsonrpccpp-common0:
 libjsonrpccpp-common0 depends on libjsoncpp0v5; however:
  Package libjsoncpp0v5 is not installed.
 libjsonrpccpp-common0 depends on libstdc++6 (>= 5.2); however:
  Version of libstdc++6:amd64 on system is 4.9.2-10.

dpkg: error processing package libjsonrpccpp-common0 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libjsonrpccpp-common0
~~~

Trying to download & install Ubuntu Wily's `libjsoncpp0v5` gives me this:

~~~
 ➜ sudo dpkg --install libjsoncpp0v5_0.10.5-1_amd64.deb
Selecting previously unselected package libjsoncpp0v5:amd64.
dpkg: considering removing libjsoncpp0 in favour of libjsoncpp0v5:amd64 ...
dpkg: no, cannot proceed with removal of libjsoncpp0 (--auto-deconfigure will help):
 llvm-3.7-dev depends on libjsoncpp0
  libjsoncpp0 is to be removed.

dpkg: regarding libjsoncpp0v5_0.10.5-1_amd64.deb containing libjsoncpp0v5:amd64:
 libjsoncpp0v5 conflicts with libjsoncpp0
  libjsoncpp0 (version 0.6.0~rc2-3.1) is present and installed.

dpkg: error processing archive libjsoncpp0v5_0.10.5-1_amd64.deb (--install):
 conflicting packages - not installing libjsoncpp0v5:amd64
Errors were encountered while processing:
 libjsoncpp0v5_0.10.5-1_amd64.deb
~~~

So it looks like I can't install `libjsoncpp0v5` without breaking `llvm`, which is also a dep for `cpp-ethereum` (the primary package I'm trying to build).
