### ISSUE TITLE
If guard missing 

### ISSUE THREAD

**Issue by andreiltd** [cinemast/libjson-rpc-cpp#162]
gcc is giving me following warning:

`jsonrpccpp/src/jsonrpccpp/client/rpcprotocolclient.cpp: In member function ‘void jsonrpc::RpcProtocolClient::throwErrorException(const Json::Value&)’:
jsonrpccpp/src/jsonrpccpp/client/rpcprotocolclient.cpp:88:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (response[KEY_ERROR].isMember(KEY_ERROR_MESSAGE) && response[KEY_ERROR][KEY_ERROR_MESSAGE].isString())
     ^~
jsonrpccpp/src/jsonrpccpp/client/rpcprotocolclient.cpp:91:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
         throw JsonRpcException(response[KEY_ERROR][KEY_ERROR_CODE].asInt(), response[KEY_ERROR][KEY_ERROR_MESSAGE].asString());
         ^~~~~`

and indeed code doesn't look like it was intended.

**Comment by cinemast** [comment]
Thank you for reporting this.
