### ISSUE TITLE
RPC call with empty parameters is rejected

### ISSUE THREAD

**Issue by JessMutant** [cinemast/libjson-rpc-cpp#164]
In rpcprotocolserverv2.cpp, there's a typo in ValidateRequestFields(). In checking the parameters type (array vs object vs null), KEY_REQUEST_PARAMETERS should be used instead of KEY_REQUEST_ID:

Line 82:   ... || request[**KEY_REQUEST_ID**].isNull()

**Comment by cinemast** [comment]
Thank you very much for detecting this. That's awkward.
