### ISSUE TITLE
SPEC file?

### ISSUE THREAD

**Issue by daniel-lucio** [cinemast/libjson-rpc-cpp#165]
Does anyone has a SPEC to build the RPM?

**Comment by cinemast** [comment]
It used to be here: https://github.com/cinemast/libjson-rpc-cpp/pull/28

But since I am not able to support it properly, I decided to drop it.

**Comment by daniel-lucio** [comment]
I was not referring to a RPM in the Makefile, I was talking about SPEC file. Which I have already do done, libjson-rpc-cpp is now available in Mageia 6.

**Comment by cinemast** [comment]
This PR also contained a spec file: https://github.com/cinemast/libjson-rpc-cpp/blob/f4e5eebd99c92920df5b854d36264f7ea2efc968/libjsonrpccpp.spec.in

Nevertheless, that is great. Do you have any reference about that or an install command that can be added to the README?

**Comment by daniel-lucio** [comment]
Yes, well I have already published the RPM for Mageia 6. To install just type:
urpmi lib64libjson-rpc-cpp0 (for 64bits)
urpmi liblibjson-rpc-cpp0 (for 32bits)
urpmi lib64libjson-rpc-cpp-devel (for devel headers)

The SRPM can be backported to Mageia 5 (but it is a manual process)

**Comment by cinemast** [comment]
Great, thanks

**Comment by cinemast** [comment]
Hi! I guess I found your spec file here: http://svnweb.mageia.org/packages/cauldron/libjson-rpc-cpp/current/SPECS/libjson-rpc-cpp.spec?view=markup&pathrev=1045066

It looks like you copied most of it from a jsoncpp spec file? 
Could you plese fix fields like Url, Description and summary to match the actual content of the package?

**Comment by cinemast** [comment]
@daniel-lucio any chance you can fix this?

**Comment by daniel-lucio** [comment]
Le 16 ao�t 2016, 10:10:42 Peter Spiess-Knafl a �crit :
> @daniel-lucio any chance you can fix this?
I will fix it this week.

I did the jsoncpp RPM thats why there are some descripts that are not correct. 
I was only focusing on making the rpm to run. I will fix it soon.

LD

**Comment by cinemast** [comment]
Great, thank you!
