### ISSUE TITLE
[Proposal] Use structs / classes to pass parameter information to the request / notification functions

### ISSUE THREAD

**Issue by SE2Dev** [cinemast/libjson-rpc-cpp#166]
Using classes or structs rather than the current method of passing parameters as function arguments makes it _much_ easier to implement things like optional parameters, etc. and have the potential to make the server stubs much easier to read / modify.

**Comment by cinemast** [comment]
Implicitly you can already do that by using `Json::Value` as parameter type.

**Comment by SE2Dev** [comment]
I did consider that, but I believe using native classes would allow users to implement their own validation methods for a given request, notification, etc.
The current va_args method seems to have some issues in that area. For example, stubgen'ed servers or clients there appears to be no way to validate that a given parameter is a 'number', as when validating it looks explicitly for either an integer or a decimal number depending on how the parameter was defined in the server / client.

**Comment by cinemast** [comment]
Well in that case, you can also use `Json::Value` as parameter type, and check within the method itself for `isNumber()`.

**Comment by cinemast** [comment]
Exactly. Alternatively this also works for the stub generator, just put in an empty object as parameter value.
