### ISSUE TITLE
Please use poll or epoll(if possible) by default.

### ISSUE THREAD

**Issue by zhangyafeikimi** [cinemast/libjson-rpc-cpp#170]
"select" has a critical issue with FD_SETSIZE.
When the lowest available fd number is larger than FD_SETSIZE, server refuses to serve anything with select.

**Comment by zhangyafeikimi** [comment]
Please check out the MHD manual:
https://www.gnu.org/software/libmicrohttpd/manual/libmicrohttpd.html

grep "FD_SETSIZE"

**Comment by cinemast** [comment]
I will look into that, thank you

**Comment by zhangyafeikimi** [comment]
Thank you.
Besides that, we prefer epoll for performance considerations.

**Comment by jdmichaud** [comment]
@zhangyafeikimi, for information, poll does not exist on [Windows before Vista](https://msdn.microsoft.com/en-us/library/windows/desktop/ms741669(v=vs.85).aspx) and its implementation seems to be broken on [macOS](https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/).

**Comment by zhangyafeikimi** [comment]
@jdmichaud , what i want to say is the library should prefer epoll IF POSSIBLE.
Do you want me to list the platform checking macros?

**Comment by zhangyafeikimi** [comment]
@jdmichaud We should always avoid select. With select, servers are only toys.

**Comment by cinemast** [comment]
I would also prefer a complete PR that introduces the switch to epoll. Could you please be a little bit more specific, why servers are toys when using select?

**Comment by zhangyafeikimi** [comment]
hi, @cinemast.
See my first comment.
Servers refusing to serve are toys, aren't they?

**Comment by cinemast** [comment]
Alright. Could you prepare a working PR for that?

**Comment by zhangyafeikimi** [comment]
Sure. I will make it if you'd like to accept it.

My private patch is based on v0.6.0. Give me some time.

**Comment by zhangyafeikimi** [comment]
#175

**Comment by cinemast** [comment]
Thanks for providing a fix.

**Comment by zhangyafeikimi** [comment]
You'd better notice at the README.md that:

POLL ON MAC 10.12 IS BROKEN.
and 
SELECT can only handle fds less than FD_SETSIZE.

It is perfect on a modern(means has epoll) linux, and basically perfect on mac expect 10.12.
