### ISSUE TITLE
Windows Precompiled libraries missing

### ISSUE THREAD

**Issue by HemadKh** [cinemast/libjson-rpc-cpp#174]
Static libraries: jsoncpp, libcurl, and microhttpd are missing. Their DLL's are provided. Could any provide instructions on how to build these libraries?

**Comment by cinemast** [comment]
@debris can you help out here?

**Comment by debris** [comment]
sure!

@HemadKh I'm no longer maintaining project which uses these deps, but here are our build scripts: https://github.com/ethereum/cpp-dependencies

Just open `main.bat`, comment out dependencies that you do not need, and then run the script. I hope you find it useful
