### ISSUE TITLE
last commit causes 'make' to error during install

### ISSUE THREAD

**Issue by richmelchr** [cinemast/libjson-rpc-cpp#177]
see below screen shot for error output. downloaded and used a previous version pre-October2016 and got no errors.  

![capture](https://cloud.githubusercontent.com/assets/10093812/20242424/b463e004-a8ea-11e6-9d3f-9c0c584af01b.PNG)

**Comment by cinemast** [comment]
Could you please give more details to reproduce this (OS, version, used compiler)? At least CI says its good.

Thank you

**Comment by binhonglee** [comment]
Hi, I have the same exact error I believe (as seen in the attached screenshot).

As to answering your question, I am on a
- Mid 2013 MacBook Air 11-inch
- macOS Sierra (10.12.1 (16B2555))
- default terminal

Hope this helps.

![screen shot 2016-12-07 at 12 05 36 am](https://cloud.githubusercontent.com/assets/16726210/20958088/fe5b8804-bc10-11e6-8af7-ccf9b488ff18.png)

**Comment by cinemast** [comment]
Which compiler?

**Comment by richmelchr** [comment]
compiler: cmake 3.0.2

I am running Debian 8.6 on a VirtualBox
kernel: 3.16.0-4-586

**Comment by binhonglee** [comment]
For mine, cmake version 3.6.2

**Comment by cinemast** [comment]
I will fix them in the upcoming release. Thanks for reporting.

**Comment by cinemast** [comment]
OS X is now alsow CI enabled
