### ISSUE TITLE
long int type 

### ISSUE THREAD

**Issue by cedrico2016** [cinemast/libjson-rpc-cpp#178]
Hi,
i'm new with json JSON RPC. I've read that JSON Numer size are unlimited. But they seem to be mapped only to int type in C++ ( enum jsontype_t
    {
        JSON_STRING = 1,
        JSON_BOOLEAN = 2,
        JSON_INTEGER = 3,
        JSON_REAL = 4,
        JSON_OBJECT = 5,
        JSON_ARRAY = 6
    } ; )
 How can i make if i want to map a number to a long int in c++ ? The only possiblity i've seen is to get the number as a JSON_INTEGER, and the size of the JSON_INTEGER is only 32bits.

**Comment by tvannoy** [comment]
Hi, 

I'm not exactly sure what your use case is, but since libjson-rpc-cpp uses jsoncpp as its underlying json library, you might be able to use the asInt64() member of jsoncpp's Json::Value object. 

The relevant jsoncpp documentation can be found [here](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_value.html)

**Comment by tvannoy** [comment]
Upon further thought, I don't think what I suggested above is possible. I think 64-bit int support would have to be added into the jsontype_t enum, then we'd have to define a way for the autogen json specification file to differentiate between 32-bit and 64-bit ints.

I think it's definitely possible to add 64-bit int.

**Comment by cinemast** [comment]
You can always use the object or array type in the stub specification. This will create code for a `Json::Value` parameter in the method.

Example:

```
[
    {
        "name": "addLargeInt",
        "params": { 
            "a": {}
            "b": {}
        },
        "returns" : {}
    }
]
```

**Comment by Jeffwhen** [comment]
https://github.com/cinemast/libjson-rpc-cpp/blob/c5387ba0cdfdc5bafd8b9c374ebd1c41aa856ef5/src/jsonrpccpp/common/procedure.cpp#L145-L148

But params validator does not allow such request.
