### ISSUE TITLE
Travis CI doesn't run every test

### ISSUE THREAD

**Issue by tvannoy** [cinemast/libjson-rpc-cpp#179]
The CI build only tests http client and unix sockets clients. 

$ cmake -DCMAKE_BUILD_TYPE=Debug -DHTTP_CLIENT=${HTTP_CLIENT} -DHTTP_SERVER=${HTTP_SERVER} -DCOMPILE_STUBGEN=${COMPILE_STUBGEN} ..
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- UNIX_DOMAIN_SOCKET_SERVER: YES
-- UNIX_DOMAIN_SOCKET_CLIENT: YES
-- TCP_SOCKET_SERVER: NO
-- TCP_SOCKET_CLIENT: NO
-- HTTP_SERVER: YES
-- HTTP_CLIENT: YES
-- UNIXDOMAINSOCKET_SERVER: YES
-- UNIXDOMAINSOCKET_CLIENT: YES
-- COMPILE_TESTS: YES
-- COMPILE_STUBGEN: YES
-- COMPILE_EXAMPLES: YES

**Comment by cinemast** [comment]
oooops. Thank you for noticing this. I will fix it.
