### ISSUE TITLE
Optionally embed microhttpd library

### ISSUE THREAD

**Issue by chfast** [cinemast/libjson-rpc-cpp#189]
This is just a suggestion. The library microhttpd is not available on every system (e.g. Windows, Alpine Linux). Would you consider optionally embedding its source code using CMake's ExternalProject module? I can help with that.

This will also help with issue related to incompatible version of microhttpd like https://github.com/cinemast/libjson-rpc-cpp/issues/180.

**Comment by cinemast** [comment]
Using externalproject add would be fine. Embedding the source code is not a possible solution for me. If you could help with that it would be great. You can take a look how it was done for the catch library.

**Comment by cinemast** [comment]
#180 is fixed now.

**Comment by chfast** [comment]
How it was fixed?
