### ISSUE TITLE
Can't build current git clones in raspbian

### ISSUE THREAD

**Issue by maso27** [cinemast/libjson-rpc-cpp#190]
I'm trying to build this on a raspberry pi, and can't get it to build from the current git branches.

When I use _master_, I get:
`error: ‘MHD_USE_EPOLL_INTERNALLY’ was not declared in this scope`
which seems to be related to an older version of libmicrohttpd.

When I use _develop_, I get:
`filedescriptorclient.cpp:46:92: error: no matching function for call to ‘min(std::basic_string<char>::size_type, long unsigned int)’`

I can successfully build from the latest on the _Releases_ page, but can't build anything newer than that.

**Comment by martijnmumbles** [comment]
Have you tried the fix described here on master? https://github.com/cinemast/libjson-rpc-cpp/commit/60f3deec022b35fc1f4c839b0a30e89654975c6f

**Comment by maso27** [comment]
Yes.  

I made those changes manually to _master_, then wound up with an error similar to that of _develop_ listed above.

**Comment by cinemast** [comment]
Which version of GCC are you using?

**Comment by maso27** [comment]
_gcc -v_ reveals:
`gcc version 4.9.2 (Raspbian 4.9.2-10)`

**Comment by cinemast** [comment]
The above commit fixes the problem. Thank you for reporting this. I will include in the next release that I am currently preparing.
