### ISSUE TITLE
In function more than 10 parameters.

### ISSUE THREAD

**Issue by Besik** [cinemast/libjson-rpc-cpp#193]
If you create a method in which the input parameters are greater than 10, then they are not properly located in the generated files.

file:         specificationparser.cpp
method: GetPositionalParameters

paramname << "param" <<  (i + 1);
replaced by
paramname << "param" << std::setfill('0') << std::setw(2) << (i + 1);

**Comment by cinemast** [comment]
Thanks for raising the issue. I will fix it in the next release.
