### ISSUE TITLE
MinGW DLLs missing in Windows binary package

### ISSUE THREAD

**Issue by Phoenox** [cinemast/libjson-rpc-cpp#199]
Just installed the precompiled binaries for Windows (version 0.5).

However, I cannot start the `jsonrpcstub.exe`. I get an error message saying that `libgcc_s_dw2-1.dll` is missing.

After I copied the files `libgcc_s_dw2-1.dll`, `libwinpthread-1.dll` and `libstdc++-6.dll` to the `bin` directory, the executable starts, but crashes when I try to generate the stubs. I tried with the MinGW DLLs from MinGW 4.9 and 5.3.

**Comment by umod47** [comment]
Same bug. The library is not usable in Windows.
I've tried libraries from mingw 4.8 and mingw 5.3.
I'm able to start the application without any arguments, but it crashes as long as i try to provide specification via command line.

**Comment by cinemast** [comment]
I know the windows support is currently sucking big time. Once I got the next release out, proper windows support (maybe through appveyour) will be the next milestone.
