### ISSUE TITLE
redis connector unit tests

### ISSUE THREAD

**Issue by jmassey-jacques** [cinemast/libjson-rpc-cpp#202]
Hi. I'm working on creating a connector that uses redis queue's a back end.

I've followed the style of unit/integration tests used for the other connectors, where a client and server are created with a mock handler, however, for the redis connector this style of integration tests require a redis server to be running at the same time. Is that okay? Do you have any other ideas for how this can be better tested?

It's not ready yet, but if you want to take a look the code can be seen here:
https://github.com/jmassey-jacques/libjson-rpc-cpp/tree/feature/redis

Thanks.

**Comment by cinemast** [comment]
Hi!
That is great news. Thanks for your upcoming contributions. I find the idea of integrating redis-support very nice.

Well requiring redis to be started upfront is probably a problem. Nevertheless a quick solution would be to start the redis server with a given configuration using the `execve` and fork commands to boot up a redis-server before the tests are run and then kill the redis-server process again.

Also don't forget to install the dependency for the travis build. Let me know if you need further advice. I'd really like to see this feature in libjson-rpc-cpp.

Thanks!

**Comment by cinemast** [comment]
Thanks again for contributing!
