### ISSUE TITLE
Common/procedure.cpp

### ISSUE THREAD

**Issue by McRemco** [cinemast/libjson-rpc-cpp#208]
Just scanning through your code and found this on line 58:
`bool Procedure::ValdiateParameters(const Json::Value &parameters) const `

Shouldn't "valdiate"  be validate?

`bool Procedure::ValidateParameters(const Json::Value &parameters) const `

**Comment by cinemast** [comment]
It should! Thank you for reporting.

**Comment by cinemast** [comment]
Commit https://github.com/cinemast/libjson-rpc-cpp/commit/34bb02d7f927e2cb11c36ebf8e09898edf853f6a fixes this issue.
