### ISSUE TITLE
Latest release doesn't work on Centos/RedHat 7

### ISSUE THREAD

**Issue by laudrup** [cinemast/libjson-rpc-cpp#209]
I don't know if you find this important, but I would at least like to inform you that the latest released version (v1.0.0) doesn't build on Centos/Redhat 7.

The reason is, that these distributions are extremely conservative and libjson-rpc-cpp depends the macros **MHD_is_feature_supported** and **MHD_FEATURE_POLL** in libmicrohttpd that are only available in 0.9.34 and newer.

I will try to find a workaround for this in the code base where I'm using your fine library, but I think you might be interested in knowing that.

Maybe it would at least be nice to test that the version of libmicrohttpd is at least 0.9.34?

Thanks.

**Comment by nsoms** [comment]
Also, it doesn't builds because of cmake 3.0 requirement, as I have found today.

**Comment by cinemast** [comment]
CentOS is always a problem with its very outdated software versions. I don't think I will support such old dependencies. @laudrup do you think it can be fixed with minor tweaks?

**Comment by laudrup** [comment]
CentOS and Red Hat are indeed problematic, but unfortunately we have to support it where I work. :-(

I haven't found any other solution that to build libmicrohttpd from source. I think it's perfectly OK that your library requires a fairly recent version of libmicrohttpd (Centos ships with a version from 2013).

It might be nice if your CMake scripts or something else detected if the version was too old instead of getting some compilation error, but it was really not that hard to figure out, so not that important.

So in short, I think it's perfectly fine that you don't support CentOS and Red Hat (without some tweaks at least). Just thought you might want to know that.

It's perfectly fine by me if you just close this issue. It might be worth considering to mention that these platforms are not supported "out of the box", but then again, there are probably many other distributions that don't work and I think it's perfectly fine to expect the user to have to make tweaks in order to support those platforms.

You have already documented support for Debian, Arch, Gentoo, MacOsX and Windows. I think it's fine to say that those are the supported platforms. If anyone wants to use anything else, they're "on their own" :-)

**Comment by cinemast** [comment]
Thank you for reporting this anyway. It might be help to others stumbling on the same error.
