### ISSUE TITLE
Avoid using a signal handler in libcurl

### ISSUE THREAD

**Issue by laudrup** [cinemast/libjson-rpc-cpp#210]
Libcurl by default adds a signal handler. This can cause very hard to debug errors in multithreaded applications as it is not well defined which thread will receive the signal.

Consider adding CURLOPT_NOSIGNAL to the options given to curl_easy_setopt to avoid this behaviour.

See here for more information:

https://curl.haxx.se/libcurl/c/CURLOPT_NOSIGNAL.html

I can make a pull request if you prefer, but this should be extremely simple to add.

**Comment by cinemast** [comment]
Thanks for detecting this. I will fix it in the next release.

**Comment by laudrup** [comment]
Great, thanks. This silly "feature" in curl can give some really weird crashes at runtime that are in no way related to your code.
