### ISSUE TITLE
ubuntu cmake fail

### ISSUE THREAD

**Issue by yushizhao** [cinemast/libjson-rpc-cpp#214]
Here are lines from CmakeError.log.
'''
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/suiqiu/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp
...
CMakeFiles/cmTC_66bf7.dir/CheckSymbolExists.c.o：in function ‘main’：
CheckSymbolExists.c:(.text+0x16)：‘pthread_create’ undefined reference
...
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_4c47f.dir/CheckFunctionExists.c.o  -o cmTC_4c47f -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
...
'''
Is it a cmake bug? Do you happen to know how to solve it?

**Comment by cinemast** [comment]
Which ubuntu version are we talking about?

**Comment by yushizhao** [comment]
@cinemast ubuntu 16.04

**Comment by yushizhao** [comment]
@cinemast cmake 3.5.1

**Comment by cinemast** [comment]
That is odd, since the CI build is working on Ubuntu 16.04: https://travis-ci.org/cinemast/libjson-rpc-cpp/jobs/325044800

**Comment by cinemast** [comment]
Please reopen if this is still an issue.
