### ISSUE TITLE
ubuntu apt-get update

### ISSUE THREAD

**Issue by yushizhao** [cinemast/libjson-rpc-cpp#215]
ubuntu apt-get install libjsonrpccpp-dev gives me version v0.6.0. Is there a way to install the latest version?

**Comment by cinemast** [comment]
You can always compile it on your own. The build process is well documented in the README.md. You can also take a look at [.travis.yml](https://github.com/cinemast/libjson-rpc-cpp/blob/master/.travis.yml).
