### ISSUE TITLE
strange dependencies

### ISSUE THREAD

**Issue by christophsturm** [cinemast/libjson-rpc-cpp#216]
why would a json rpc library depend on a redis client lib?

**Comment by cinemast** [comment]
Hi Christoph!
The dependencies are optional as documented in the [README Build section](https://github.com/cinemast/libjson-rpc-cpp/tree/develop#Build).

libmicrohttpd, libredisclient, etc. are used for the connectors that are shipped with this library. The minimal dependency you need is `libjsoncpp`.

Please reopen the issue if you have further questions.
