### ISSUE TITLE
Linker error while building...

### ISSUE THREAD

**Issue by kiranbhide** [cinemast/libjson-rpc-cpp#218]
I have a issue compiling v1.0.0
Tried different cmake settings to resolve it, but no luck... kindly support

**System**: Ubuntu 14.04.5 LTS
**Compiler**: c++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
**Dependencies installed**: argtable2-13, hiredis-0.13.3, libmicrohttpd-0.9.55, jsoncpp-1.8.3

[ 51%] Linking CXX executable ../../bin/jsonrpcstub
cd /home/XXX/misc/json-rpc/libjson-rpc-cpp-1.0.0/build/src/stubgenerator && /usr/bin/cmake -E cmake_link_script CMakeFiles/jsonrpcstub.dir/link.txt --verbose=1
/usr/bin/c++    -std=c++11 -fprofile-arcs -ftest-coverage   CMakeFiles/jsonrpcstub.dir/main.cpp.o  -o ../../bin/jsonrpcstub -rdynamic ../../lib/libjsonrpccpp-stub.so.1.0.0 ../../lib/libjsonrpccpp-common.so.1.0.0 /usr/local/lib/x86_64-linux-gnu/libjsoncpp.so /usr/local/lib/libargtable2.so -Wl,-rpath,/home/XXX/misc/json-rpc/libjson-rpc-cpp-1.0.0/build/lib:/usr/local/lib/x86_64-linux-gnu:/usr/local/lib: 
../../lib/libjsonrpccpp-common.so.1.0.0: undefined reference to `Json::Value::append(Json::Value&&)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/jsonrpcstub] Error 1
make[2]: Leaving directory `/home/XXX/misc/json-rpc/libjson-rpc-cpp-1.0.0/build'
make[1]: *** [src/stubgenerator/CMakeFiles/jsonrpcstub.dir/all] Error 2
make[1]: Leaving directory `/home/XXX/misc/json-rpc/libjson-rpc-cpp-1.0.0/build'
make: *** [all] Error 2

**Comment by cinemast** [comment]
I am sorry, 14.04 is too old to be supported on my end.
