### ISSUE TITLE
Link error building the "Using the framework" example

### ISSUE THREAD

**Issue by x-martian** [cinemast/libjson-rpc-cpp#223]
I got link error in building the server example.  The following are the outline of the procedures taken to build the example:

OS: ubuntu 16.04 LTS

Building libjson-rpc-cpp:

`git clone git://github.com/cinemast/libjson-rpc-cpp.git`
`mkdir -p libjson-rpc-cpp/build`
`cd libjson-rpc-cpp/build`
`cmake -DHTTP_CLIENT=NO -DHTTP_SERVER=NO -DREDIS_SERVER=NO -DREDIS_CLIENT=NO -DTCP_SOCKET_SERVER=YES .. && make`
`sudo make install`
`sudo ldconfig`

Build the example:

'g++ helloworldlinuxgcc.cpp -ljsoncpp -ljsonrpccpp-common -ljsonrpccpp-server -o sampleserver -std=gnu++11'

Got the following link errors:

/tmp/cc2LOZwo.o: In function `main':
helloworldlinuxgcc.cpp:(.text+0x123): undefined reference to `jsonrpc::LinuxTcpSocketServer::LinuxTcpSocketServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int const&, unsigned long)'
helloworldlinuxgcc.cpp:(.text+0x1a0): undefined reference to `jsonrpc::LinuxTcpSocketServer::~LinuxTcpSocketServer()'
helloworldlinuxgcc.cpp:(.text+0x20a): undefined reference to `jsonrpc::LinuxTcpSocketServer::~LinuxTcpSocketServer()'
collect2: error: ld returned 1 exit status

nm -D /usr/local/lib/libjsonrpccpp-server.so.1.0.0 | grep Linux
000000000009874e T _ZN7jsonrpc20LinuxTcpSocketServer10CleanCloseERKi
0000000000098660 T _ZN7jsonrpc20LinuxTcpSocketServer12CloseByResetERKi
000000000009857c T _ZN7jsonrpc20LinuxTcpSocketServer15WaitClientCloseERKiS2_
000000000009827c T _ZN7jsonrpc20LinuxTcpSocketServer16HandleConnectionEi
00000000000981c6 T _ZN7jsonrpc20LinuxTcpSocketServer18CheckForConnectionEv
0000000000097f38 T _ZN7jsonrpc20LinuxTcpSocketServer18InitializeListenerEv
0000000000097cfe T _ZN7jsonrpc20LinuxTcpSocketServerC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKjm
0000000000097cfe T _ZN7jsonrpc20LinuxTcpSocketServerC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKjm
0000000000097edc T _ZN7jsonrpc20LinuxTcpSocketServerD0Ev
0000000000097de4 T _ZN7jsonrpc20LinuxTcpSocketServerD1Ev
0000000000097de4 T _ZN7jsonrpc20LinuxTcpSocketServerD2Ev
00000000002abb60 V _ZTIN7jsonrpc20LinuxTcpSocketServerE
000000000009c020 V _ZTSN7jsonrpc20LinuxTcpSocketServerE
00000000002abb18 V _ZTVN7jsonrpc20LinuxTcpSocketServerE

The source code:

#include <iostream>
using namespace std;

#include "abstractstubserver.h"
#include <jsonrpccpp/server/connectors/linuxtcpsocketserver.h>
#include <jsonrpccpp/server/connectors/filedescriptorserver.h>
//#include "linuxtcpsocketserver.h"

using namespace jsonrpc;
using namespace std;

class MyStubServer : public AbstractStubServer
{
    public:
        MyStubServer(AbstractServerConnector &connector);

        virtual void notifyServer();
        virtual std::string sayHello(const std::string& name);
};

MyStubServer::MyStubServer(AbstractServerConnector &connector) :
    AbstractStubServer(connector)
{
}
void MyStubServer::notifyServer()
{
    cout << "Server got notified" << endl;
}
string MyStubServer::sayHello(const

**Comment by cinemast** [comment]
Sorry for the late answer. I cannot reproduce your error on a fresh compile. Have you tried wiping the build directory? Could you share the helloworldlinux.cpp file?

**Comment by cinemast** [comment]
Please reopen this issue if you are still experiencing problems.
