### ISSUE TITLE
/usr/bin/ld: cannot find -lpthreads

### ISSUE THREAD

**Issue by sonyangchang** [cinemast/libjson-rpc-cpp#230]
When I build the library，I got this error."/usr/bin/ld: cannot find -lpthreads" in CMakeError.log. I  dont know how to get get the problem solved.
It seems other guys stumble into similar problem. https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads

**Comment by cinemast** [comment]
Please provide some details on your system and reopen.

**Comment by 405755490** [comment]
I have the same problem. 
----  dependencies    some are not installed（libmicrohttpd libargtable catch）
libcurl
libmicrohttpd
libjsoncpp
libargtable
cmake
libhiredis
catch
------------------
Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jul 4 15:04:05 UTC 2017

cmake version 3.5.2
--------------------
error info:
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_a1724.dir/CheckFunctionExists.c.o  -o cmTC_a1724 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
...
