### ISSUE TITLE
Client connector error: libcurl error: 2

### ISSUE THREAD

**Issue by pangwong** [cinemast/libjson-rpc-cpp#231]
There are random jsonrpc::exception as the title show.  I completely has no idea why this happened even after I read the curl error list.  Any explanation will be welcome.
I use the old version 0.6.0.

**Comment by cinemast** [comment]
Please try the new version and see if it fixes the problem.
[curl error list](https://curl.haxx.se/libcurl/c/libcurl-errors.html) suggests a ressource prolbem for error 2:

```
CURLE_FAILED_INIT (2)

Very early initialization code failed. This is likely to be an internal error or problem, or a resource problem where something fundamental couldn't get done at init time. 
```

**Comment by pangwong** [comment]
Finally I found the reason that using the same stub_client in different threads.
