### ISSUE TITLE
Batch request produces invalid JSON

### ISSUE THREAD

**Issue by mining-visualizer** [cinemast/libjson-rpc-cpp#232]
If I send a request (non-batch) which does not require anything in the params part I use this C++ code:

```c+
result = CallMethod("method_1", Json::Value());
```

it produces the following JSON, which seems fine

```json
{
	"id":1,
	"json rpc": "2.0",
	"method": "method_1"
}
```

But if I do something similar with a batch request, ie
```c++
jsonrpc::BatchCall batchCall = jsonrpc::BatchCall();

int id1= batchCall.addCall("method_1", Json::Value());
int id2= batchCall.addCall("method_2", Json::Value());

jsonrpc::BatchResponse response = CallProcedures(batchCall);
```

it produces the following JSON (notice the "params" element)
```json
[
  {
    "id": 1,
    "jsonrpc": "2.0",
    "method": "method_1",
    "params": null
  },
  {
    "id": 2,
    "jsonrpc": "2.0",
    "method": "method_2",
    "params": null
  },
]
```

I am interacting with  Node.js server running the 'jayson' package.  It reports this as 'error: -32600, Invalid request'.  Is this a bug in your package, or in the 'jayson' package?

**Comment by cinemast** [comment]
Well, the standard does not really specify. But de behavior should be consistent. Did you also raise a discussion in the jayson package?
