### ISSUE TITLE
For batch requests, getErrorCode and getErrorMessage don't work

### ISSUE THREAD

**Issue by mining-visualizer** [cinemast/libjson-rpc-cpp#233]
This is a follow-up to #232 

Consider the following code.  It produces invalid json code (according to the `jayson` package).  I test `hasErrors` after the call,  which returns true, so I then try to determine the actual errors, but I don't get any values back from `getErrorCode` or `getErrorMessage`

```c++
jsonrpc::BatchCall batchCall = jsonrpc::BatchCall();

int id1= batchCall.addCall("method_1", Json::Value());
int id2= batchCall.addCall("method_2", Json::Value());

jsonrpc::BatchResponse response = CallProcedures(batchCall);

if (response.hasErrors())
{
	cout << "hasErrors = true";
	cout << response.getErrorCode(id1) << ", " << response.getErrorCode(id2);
	cout << response.getErrorMessage(id1) << ", " << response.getErrorMessage(id2) ;
}
```

The screen output for this is:
```
hasErrors = true
0, 0
,
```

So it seems  `getErrorCode` or `getErrorMessage` are not returning anything.

**Comment by cinemast** [comment]
Please post the content of the server's response.

**Comment by mining-visualizer** [comment]
I don't have my software configured for testing this issue anymore.  Maybe you can do that.
