### ISSUE TITLE
supporting Language Server Protocol (LSP)

### ISSUE THREAD

**Issue by fferri** [cinemast/libjson-rpc-cpp#235]
Since the C++ client is missing from [language server protocol (LSP)](https://langserver.org/), I'm attempting to write one.

In their [TypeScript spec](https://microsoft.github.io/language-server-protocol/specification) I see fields that can be a type or  null, and also fields which are optional, e.g.:

```
interface InitializeParams {
	/**
	 * The process Id of the parent process that started
	 * the server. Is null if the process has not been started by another process.
	 * If the parent process is not alive then the server should exit (see exit notification) its process.
	 */
	processId: number | null;

	/**
	 * The rootPath of the workspace. Is null
	 * if no folder is open.
	 *
	 * @deprecated in favour of rootUri.
	 */
	rootPath?: string | null;
    ...
```

how to encode these in the libjson-rpc-cpp spec?

Also, according to LSP, the client is run as a child process. How to connect to this? filedescriptorclient?

**Comment by cinemast** [comment]
@fferri are you still interested in this? I am not sure I understood you entirely. According to the URL a C++ client already exists. Currently it is not possible to have alternate types.

**Comment by cinemast** [comment]
I could add a `null` literal to the spec which would deactivate the type checking on the server side.

**Comment by cinemast** [comment]
I think the whole idea behind the spec is type checking, so If type checking needs to be deactivated, please manually bind the methods by ommiting the type info in the Procedure declarations.

**Comment by fferri** [comment]
IMHO, an optional field should not deactivate type checking.

**Comment by cinemast** [comment]
You could take a look at my new implementation: https://github.com/jsonrpcx/json-rpc-cxx it supports variants and optionals of c++17, which might be better suited here.
