### ISSUE TITLE
Please use the cmake find module from jsoncpp instead of your own

### ISSUE THREAD

**Issue by strahlc** [cinemast/libjson-rpc-cpp#238]
All packages that are using libjson-rpc-cpp need to find jsoncpp also, but uses the original find module from jsoncpp, which differs from your find module.
This causes build problems with openembedded and bitbake, but also in normal Linux distributions.

**Comment by cinemast** [comment]
Thanks, I will switch in the next release.

**Comment by cinemast** [comment]
I could not find an "official" FindModule in current CMake distributions. Do you have a reference to that?

**Comment by strahlc** [comment]
**jsoncpp** installs its own find module during the installation of the package.

https://github.com/open-source-parsers/jsoncpp/blob/2baad4923e6d9a7e09982cfa4b1c5fd0b67ebd87/CMakeLists.txt#L150

**Comment by cinemast** [comment]
I just discovered, that this find module does not get installed on ArchLinux (and maybe others).

https://www.archlinux.org/packages/extra/x86_64/jsoncpp/

As long as this is the case, I cannot remove it.

**Comment by ccope** [comment]
Looks like upstream is migrating to meson and no longer updating cmake configs (from comments on the Arch bug)

**Comment by cinemast** [comment]
Thanks for the info. I'll keep my version for now.
