### ISSUE TITLE
Not able to create sample on WindowsOS

### ISSUE THREAD

**Issue by swanandb2** [cinemast/libjson-rpc-cpp#240]
I have installed windows installer for JSON RPC and then tried to build example as mention in section.
As of now, I am using mingw compiler on windows. Code gets compile successfully but got error in linker steps. Linker was not able to locate curl and jsoncpp libs.
I tried searching under lib directories those are not present corresponding dll are present and deployed with installer.
Kindly help me to locate this lib file.

**Comment by cinemast** [comment]
Windows is currently not supported.
