### ISSUE TITLE
got trouble with simpleserver.cpp 

### ISSUE THREAD

**Issue by wallhisg** [cinemast/libjson-rpc-cpp#243]
I'm testing with your lib, and try the simpleserver.cpp example 
1) with code
    HttpServer server(8383);
    SampleServer serv(server);
Issues:
JsonRpc/SimpleServer/SimpleServer.o: In function `jsonrpc::HttpServer::~HttpServer()':
SimpleServer.cpp:(.text._ZN7jsonrpc10HttpServerD2Ev[_ZN7jsonrpc10HttpServerD5Ev]+0x4): undefined reference to `vtable for jsonrpc::HttpServer'

2) and code 
    HttpServer server(8383, nullptr, nullptr, 50);
    SampleServer serv(server);
Issues:
SimpleServer.cpp:(.text._ZN7jsonrpc10HttpServerD2Ev[_ZN7jsonrpc10HttpServerD5Ev]+0x4): undefined reference to `vtable for jsonrpc::HttpServer'
JsonRpc/SimpleServer/SimpleServer.o: In function `jsonrpc::HttpServer::~HttpServer()':
SimpleServer.cpp:(.text._ZN7jsonrpc10HttpServerD0Ev[_ZN7jsonrpc10HttpServerD5Ev]+0x4): undefined reference to `vtable for jsonrpc::HttpServer'
collect2: error: ld returned 1 exit status

OS: Ubuntu 18.04
Could you please show me what wrong?
Thank you.

**Comment by cinemast** [comment]
Did you link against the required libraries, as stated in the README?
`g++ main.cpp -ljsoncpp -lmicrohttpd -ljsonrpccpp-common -ljsonrpccpp-server -o sampleserver`

What is your compile command?.

**Comment by wallhisg** [comment]
I missed the required libraries when linking.
and now it worked.
Thank you!
