### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cinemast/libjson-rpc-cpp#245]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [TcpSocketClient](https://github.com/cinemast/libjson-rpc-cpp/blob/e960bf5c00489dd2451be087ac4f05c9e5a47aa4/src/jsonrpccpp/client/connectors/tcpsocketclient.cpp#L30 "Destructor for TcpSocketClient")
- [TcpSocketServer](https://github.com/cinemast/libjson-rpc-cpp/blob/e960bf5c00489dd2451be087ac4f05c9e5a47aa4/src/jsonrpccpp/server/connectors/tcpsocketserver.cpp#L31 "Destructor for TcpSocketServer")

**Comment by psk-ixolit** [comment]
Thanks for reporting it, I was not aware of this behavior.

**Comment by cinemast** [comment]
Thanks for reporting. I was not aware of this behavior.
