### ISSUE TITLE
Being able to return errors from a method callback

### ISSUE THREAD

**Issue by adriweb** [cinemast/libjson-rpc-cpp#249]
Hi,

I'd like to know if, for methods, there's a way to return errors ourselves (for instance, if some specific request content/value isn't valid) instead of just filling the response value (that's fine when everything's as expected)
It's OK for me if I have to write the full response JSON myself, I guess, but my feeling is that we're possibly a bit too limited right now as to what we can access from the method callbacks, unless I missed something.

Thank you!

**Comment by cinemast** [comment]
I totally agree. I thought I implemented exception handling for callbacks, but it appears I didn't.

**Comment by cinemast** [comment]
Actually I did implement. I extended the examples.

**Comment by adriweb** [comment]
Ah, right - but I was talking about methods directly, like here https://github.com/cinemast/libjson-rpc-cpp/blob/3ec1ce29c425f6adceb94da6a16e732df783b798/src/examples/filedescriptorserver.cpp#L57
But I haven't actually tried that yet, maybe it works fine - I'll see in a couple hours...
