### ISSUE TITLE
-lhredis is not removed, when -DREDIS_SERVER=NO -DREDIS_CLIENT=NO

### ISSUE THREAD

**Issue by RyuMaster** [cinemast/libjson-rpc-cpp#250]
Hi! When I pass -DREDIS_SERVER=NO -DREDIS_CLIENT=NO to cmake, it still has -lhredis inside *.pc files; Later on, this brings to linker errors, when using libjson-rpc-cpp with outher libraries, like trying to make shared library for windows using mingw (no undefined symbols allowed)

**Comment by cinemast** [comment]
Thanks for reporting this. I will fix it in the next release.
