### ISSUE TITLE
Support Catch2?

### ISSUE THREAD

**Issue by mgorny** [cinemast/libjson-rpc-cpp#251]
It seems that Catch has been 'upgraded' to [Catch2](https://github.com/catchorg/Catch2) which seems incompatible with the legacy version. Most notably, all files seem to be named 'Catch2' instead of 'Catch' now. Could you please look into upgrading to avoid depending on obsolete versions?

**Comment by cinemast** [comment]
Do you hava a reference for the names being `Catch2` instead of `Catch`? The header file appears to still be named `catch.hpp`.

**Comment by mgorny** [comment]
I'm sorry, I was referring to the standard install directory, CMake and pkg-config files, i.e.:

```
 qlist catch
/usr/lib64/cmake/Catch2/Catch2Targets.cmake
/usr/lib64/cmake/Catch2/Catch2Config.cmake
/usr/lib64/cmake/Catch2/Catch2ConfigVersion.cmake
/usr/lib64/cmake/Catch2/ParseAndAddCatchTests.cmake
/usr/lib64/cmake/Catch2/Catch.cmake
/usr/lib64/cmake/Catch2/CatchAddTests.cmake
/usr/include/catch2/catch_reporter_teamcity.hpp
/usr/include/catch2/catch_reporter_tap.hpp
/usr/include/catch2/catch_reporter_automake.hpp
/usr/include/catch2/catch.hpp
[...]
/usr/share/Catch2/gdbinit
/usr/share/Catch2/lldbinit
/usr/share/pkgconfig/catch2.pc
```

Apparently no code changes are required, so it should be a matter of replacing custom `find_package(Catch)` with `find_package(Catch2)` and other refs accordingly. I'll give it a shot and submit a PR if I succeed.

**Comment by mgorny** [comment]
Hmm, I see that upstream actually *expects* you to `#include <catch2/catch.h>`.

**Comment by Tim-S** [comment]
I can confirm that no code changes are required as building with 
```bash
cmake .. -DCATCH_INCLUDE_DIR=/usr/local/include/catch2
```
works.

**Comment by cinemast** [comment]
Do you have a reference for that? I find inconsistent examples everywhere.

**Comment by cinemast** [comment]
Nevermind, I updated the cmake script to use a newer version of catch and found the issue.
