### ISSUE TITLE
libjson-rpc-cppTargets.cmake: incorrect INTERFACE_LINK_LIBRARIES

### ISSUE THREAD

**Issue by justusranvier** [cinemast/libjson-rpc-cpp#253]
INTERFACE_LINK_LIBRARIES is always set to "jsoncpp_lib_static" even if libjson-rpc-cpp was dynamically linked to jsoncpp.

If jsoncpp was installed without static libraries, libjson-rpc-cpp will compile successfully however other cmake projects that attempt to use the libjson-rpc-cpp::jsonrpcclient target will fail to link because jsoncpp_lib_static does not exist.

**Comment by cinemast** [comment]
Thasnk for detecting and reporting this!
