### ISSUE TITLE
Latest release doesn't work on CentOS 7

### ISSUE THREAD

**Issue by Timolol2012** [cinemast/libjson-rpc-cpp#258]
sudo rpm -Uvh https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
yum clean all
yum makecache
sudo yum update

sudo yum -y install gcc gcc-c++ cmake3 wget git libcurl-devel jsoncpp-devel argtable-devel hiredis-devel

wget https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.62.tar.gz
tar -zxvf libmicrohttpd-0.9.62.tar.gz && cd libmicrohttpd-0.9.62 && ./configure
sudo make
sudo make install
sudo ldconfig

git clone git://github.com/cinemast/libjson-rpc-cpp.git
mkdir -p libjson-rpc-cpp/build && cd libjson-rpc-cpp/build
cmake3 .. && make

$ cmake3 .. && make
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:21 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- UNIX_DOMAIN_SOCKET_SERVER: NO
-- UNIX_DOMAIN_SOCKET_CLIENT: NO
-- TCP_SOCKET_SERVER: NO
-- TCP_SOCKET_CLIENT: NO
-- HTTP_SERVER: YES
-- HTTP_CLIENT: YES
-- REDIS_SERVER: YES
-- REDIS_CLIENT: YES
-- UNIXDOMAINSOCKET_SERVER: NO
-- UNIXDOMAINSOCKET_CLIENT: NO
-- COMPILE_TESTS: YES
-- COMPILE_STUBGEN: YES
-- COMPILE_EXAMPLES: YES
-- Found jsoncpp: /usr/include  
-- Jsoncpp header: /usr/include
-- Jsoncpp lib   : /usr/lib64/libjsoncpp.so
-- Found argtable: /usr/include  
-- Argtable header: /usr/include
-- Argtable lib   : /usr/lib64/libargtable2.so
-- Found CURL: /usr/lib64/libcurl.so (found version "7.29.0") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CURL header: /usr/include
-- CURL lib   : /usr/lib64/libcurl.so
-- Found mhd: /usr/local/include  
-- MHD header: /usr/local/include
-- MHD lib   : /usr/local/lib/libmicrohttpd.so
-- Found hiredis: /usr/include  
-- Hiredis header: /usr/include
-- Hiredis lib   : /usr/lib64/libhiredis.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find catch (missing: CATCH_INCLUDE_DIR) 
-- Could not find catch, downloading it now
-- Catch directory: /home/vnscoin/libjson-rpc-cpp/build/catch/src/catch/single_include 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vnscoin/libjson-rpc-cpp/build
Scanning dependencies of target catch
[  1%] Creating directories for 'catch'
[  2%] Performing download step (download, verify and extract) for 'catch'
-- Downloading...
   dst='/home/vnscoin/libjson-rpc-cpp/build/catch/src/v2.0.1.tar.gz'
   timeout='none'
-- Using src='https://github.com/catchorg/Catch2/archive/v2.0.1.tar.gz'
-- verifying file...
       file='/home/vnscoin/libjson-rpc-cpp/build/catch/src/v2.0.1.tar.gz'
-- Downloading... done
-- extracting...
     src='/home/vnscoin/libjson-rpc-cpp/build/catch/src/v2.0.1.tar.gz'
     dst='/home/vnscoin/libjson-rpc-cpp/build/catch/src/catch'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  3%] No patch step for 'catch'
[  4%] No update step for 'catch'
[  6%] No configure step for 'catch'
[  7%] No build step for 'catch'
[  8%] No install step for 'catch'
[  9%] Completed 'catch'
[  9%] Built target catch
Scanning dependencies of target jsonrpccommon
[ 11%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/errors.cpp.o
[ 12%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/exception.cpp.o
[ 13%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/procedure.cpp.o
[ 14%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/specificationparser.cpp.o
[ 16%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/specificationwriter.cpp.o
[ 17%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/streamreader.cpp.o
[ 18%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpccommon.dir/common/streamwriter.cpp.o
[ 19%] Linking CXX shared library ../../lib/libjsonrpccpp-common.so
[ 19%] Built target jsonrpccommon
Scanning dependencies of target jsonrpcserver
[ 20%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractprotocolhandler.cpp.o
[ 22%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractserverconnector.cpp.o
[ 23%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/abstractthreadedserver.cpp.o
[ 24%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/requesthandlerfactory.cpp.o
[ 25%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/rpcprotocolserver12.cpp.o
[ 27%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/rpcprotocolserverv1.cpp.o
[ 28%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/rpcprotocolserverv2.cpp.o
[ 29%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/httpserver.cpp.o
[ 30%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcserver.dir/server/connectors/redisserver.cpp.o
[ 32%] Linking CXX shared library ../../lib/libjsonrpccpp-server.so
[ 32%] Built target jsonrpcserver
Scanning dependencies of target jsonrpcclient
[ 33%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcclient.dir/client/batchcall.cpp.o
[ 34%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcclient.dir/client/batchresponse.cpp.o
[ 35%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcclient.dir/client/client.cpp.o
[ 37%] Building CXX object src/jsonrpccpp/CMakeFiles/jsonrpcclient.dir/client/rpcprotocolclient.cpp.o
/home/vnscoin/libjson-rpc-cpp/src/jsonrpccpp/client/rpcprotocolclient.cpp: 在成员函数‘void jsonrpc::RpcProtocolClient::BuildRequest(const string&, const Json::Value&, std::string&, bool)’中:
/home/vnscoin/libjson-rpc-cpp/src/jsonrpccpp/client/rpcprotocolclient.cpp:36:12: 错误：‘class Json::FastWriter’没有名为‘omitEndingLineFeed’的成员
     writer.omitEndingLineFeed();
            ^
make[2]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcclient.dir/client/rpcprotocolclient.cpp.o] 错误 1
make[1]: *** [src/jsonrpccpp/CMakeFiles/jsonrpcclient.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by cinemast** [comment]
The libjsoncpp version you use appears to be too old to contain the `omitEndingLineFeed()` method. Since it is not that critical, you can just patch it out.

**Comment by cinemast** [comment]
Feel free to reopen this issue if you need further help.
