### ISSUE TITLE
0.7.0 version says it added ability for HttpServer to listen on localhost only

### ISSUE THREAD

**Issue by KaustubhShamshery** [cinemast/libjson-rpc-cpp#261]
However, I think this is still an outstanding issue. 
Ref : https://github.com/cinemast/libjson-rpc-cpp/releases/tag/v0.7.0

If it is indeed possible, can someone redirect me to how?

**Comment by cinemast** [comment]
Whoops, that is my bad. Currently it is not working. There used to be a PR #200. And on developr there is one that got merged (but currently doesn't work on sox) #259

**Comment by KaustubhShamshery** [comment]
Thanks for the update, I can use `TcpSocketServer` for the purpose I suppose. The issue is the ubuntu build `libjsonrpccpp-dev_0.7.0-1+b3_amd64` does not seem to feature the corresponding  header file `src/jsonrpccpp/tcpsocketserver.h` seems missing, any clue about that ?

**Comment by cinemast** [comment]
HttpServer now support BindLocalhost() functionality. The TcpSocketServer is not very reliable, therefore it is not bundled by default. If you want to use it, please build from source.
