### ISSUE TITLE
Binding method with array doesn't accept an array input

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [cinemast/libjson-rpc-cpp#262]
Hello,

For me binding with strings works fine. For example, this:
```
    this->bindAndAddMethod(jsonrpc::Procedure("sayHello", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "name", jsonrpc::JSON_STRING, nullptr), &RPCHandler::rpc_sayHello);
```
which comes from the example, works with no problems. Adding more strings is working too. But this:
```
    this->bindAndAddMethod(
        jsonrpc::Procedure("set_method", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "sessionid", jsonrpc::JSON_ARRAY, "ipv4", jsonrpc::JSON_STRING, nullptr),
  &RPCHandler::rpc_setMethod);

```
Doesn't work no matter what I do, and I keep getting an `INVALID_PARAMS` response. The following is the input I use with it:
```
{"jsonrpc": "2.0", "method": "set_method", "params": {"sessionid": "abcd", "ipv4": []}, "id": 2}
```
But see, if I change that `JSON_ARRAY` to `JSON_STRING` and make the `"ipv4"` value some string, then it works with no problems. Am I doing this wrong or is this a bug?

Thank you.

**Comment by cinemast** [comment]
Your parameter ordering is wrong. 

Take a lookt at [this example](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/examples/simpleserver.cpp#L20)

The first type definition is the return type of the method follwed by (name, type, ...). So I think what you want to achieve is the follwoing:

```
this->bindAndAddMethod(jsonrpc::Procedure("set_method", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "sessionid", jsonrpc::JSON_STRING, "ipv4", jsonrpc::JSON_ARRAY, nullptr),
  &RPCHandler::rpc_setMethod);
```

Assuming `&RPCHandler::rpc_setMethod` returns a string.

**Comment by TheQuantumPhysicist** [comment]
Thanks for the response. The return type thing solves the mystery for me (still haven't tried it on code, will do when I'm back on my setup). I'm a little confused though. Why do we need the return type? Aren't we assigning `response` manually, like the example does?

**Comment by cinemast** [comment]
The return type is used by the stubgenerator to create the pure virtual method signatures.

**Comment by TheQuantumPhysicist** [comment]
Thank you. The problem is resolved. Please consider adding comments there above sayHello to explain the parameter.
