### ISSUE TITLE
Compile issue with stubgenerator static

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [cinemast/libjson-rpc-cpp#263]
This is for tag v1.1.1.

When I compile with:
```
cmake .. -DREDIS_SERVER=NO -DREDIS_CLIENT=NO -DCOMPILE_TESTS=NO -DBUILD_SHARED_LIBS=NO -DBUILD_STATIC_LIBS=YES
```
I get the error:
```
[ 70%] Linking CXX executable ../../bin/jsonrpcstub
/usr/bin/ld: cannot find -ljsonrpccommonStatic
```
I was only able to compile with the following (by disabling stub generator):
```
cmake .. -DCOMPILE_STUBGEN=NO -DREDIS_SERVER=NO -DREDIS_CLIENT=NO -DCOMPILE_TESTS=NO -DBUILD_SHARED_LIBS=NO -DBUILD_STATIC_LIBS=YES
```
I'm on Ubuntu 18.04.

**Comment by cinemast** [comment]
You are right, there is actually a static section missing for common: https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/CMakeLists.txt#L155

**Comment by cinemast** [comment]
I thinks [this line](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/stubgenerator/CMakeLists.txt#L36) needs to be changed from `jsonrpccommonStatic` to `common`. Could you try that?

**Comment by TheQuantumPhysicist** [comment]
I left the setup now. I'll try it tomorrow.

**Comment by TheQuantumPhysicist** [comment]
That fixes the issue. Thanks.
