### ISSUE TITLE
Return error after processing user input

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [cinemast/libjson-rpc-cpp#265]
I'm not sure whether I should call this a "bug" or a feature request, but here's the problem: The json RPC system works perfectly fine, but it seems to be impossible for the developer to assign create an error that complies with jsonrpc v2. In that, the error node/object has to be in the [root of the response](https://en.wikipedia.org/wiki/JSON-RPC#Usage).

Consider [this example](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/examples/simpleserver.cpp#L29). If the user inputs the correct parameter types, but has a problem in the input, all the developer can do is return an error *inside the `result` node/object* of the response. Instead what I'm looking for is using the `error` node in the root.

Can this be done?

Btw I also noticed that `jsonrpc::Procedure` is not a virtual class, so I cannot inherit it and modify the way parameters are checked to signal errors.

**Comment by cinemast** [comment]
See in [this example](https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/examples/stubserver.cpp#L37). You can always throw a `JsonRpcException` from a procedure.

**Comment by TheQuantumPhysicist** [comment]
Thanks. That works. 

Although a note about it: it's difficult to make this work cleanly in a system that's highly fault tolerant. My design is supposed to catch any kind of exception inside `Procedure()` as having a `terminate` call should never happen. Having to throw an exception that is not supposed to be interpreted as an error from the system needed some trickery. A useful option is to have an overload of Procedure that takes an error reference.

Have a nice weekend.
