### ISSUE TITLE
Link faild with undefined reference to `MHD_is_feature_supported'

### ISSUE THREAD

**Issue by Arryboom** [cinemast/libjson-rpc-cpp#267]
- OS: Centos 7.3 x64
- Envir: GCC 7.3,CMake 3.14.2,libmicrohttpd-0.9.63(compile install)

the Old libmicrohttpd installed by yum on centos doesn't support epool,so I have to download the lastest version of libmicrohttpd then compile and install manully.then I try to compile libjsonrpccpp and got following error:

---
```
[ 51%] Built target libjsonrpcstub
Scanning dependencies of target jsonrpcstub
[ 53%] Building CXX object src/stubgenerator/CMakeFiles/jsonrpcstub.dir/main.cpp.o
[ 54%] Linking CXX executable ../../bin/jsonrpcstub
[ 54%] Built target jsonrpcstub
Scanning dependencies of target redisserversample
[ 55%] Building CXX object src/examples/CMakeFiles/redisserversample.dir/redisserver.cpp.o
[ 56%] Linking CXX executable ../../bin/redisserversample
../../lib/libjsonrpccpp-server.so.1.2.0: undefined reference to `MHD_is_feature_supported'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/redisserversample] Error 1
make[1]: *** [src/examples/CMakeFiles/redisserversample.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Arryboom** [comment]
as https://github.com/cinemast/libjson-rpc-cpp/issues/209 laudrup said,"macros MHD_is_feature_supported and MHD_FEATURE_POLL in libmicrohttpd that are only available in 0.9.34 and newer.",it should be no problem with libmicrohttpd-0.9.63,but I still got "undefined reference to `MHD_is_feature_supported'"error,my temporary way to compile libjsonrpccpp successfully is edit the 
** libjson-rpc-cpp/src/jsonrpccpp/server/connectors/httpserver.cpp **

change
```
  if (!this->running) {
    const bool has_epoll =
        (MHD_is_feature_supported(MHD_FEATURE_EPOLL) == MHD_YES);
    const bool has_poll =
        (MHD_is_feature_supported(MHD_FEATURE_POLL) == MHD_YES);
    unsigned int mhd_flags;
```
to
```
  if (!this->running) {
    const bool has_epoll =
        //(MHD_is_feature_supported(MHD_FEATURE_EPOLL) == MHD_YES);
        true;
    const bool has_poll =
        //(MHD_is_feature_supported(MHD_FEATURE_POLL) == MHD_YES);
        true;
    unsigned int mhd_flags;
```
because I know the version of  libmicrohttpd I compiled support these features.

**Comment by cinemast** [comment]
Did you uninstall the version from the package manager?

**Comment by Arryboom** [comment]
> Did you uninstall the version from the package manager?

yes i did

**Comment by cinemast** [comment]
I'll try spinning up a VM today.

**Comment by cinemast** [comment]
@Arryboom I added an example Dockerfile in the last commit. I hope this helps. It works here.
