### ISSUE TITLE
Support for numeric data type

### ISSUE THREAD

**Issue by rangatce** [cinemast/libjson-rpc-cpp#270]
In latest version of the library code, there are JSON_INTEGER and JSON_REAL data types for numeric parameters. 
If we define a method parameter type as JSON_REAL and pass a numeric value without decimal place (ex: 5), INVALID PARAM exception is being raised by the server (as 5 is not of type double).
Hence, a number is required to be passed always with a decimal place (ex 5.0).

To overcome this, I am planning to add a new data type called JSON_NUMERIC which takes integer/double values.
  case JSON_NUMERIC:
    if (!value.isNumeric())
      ok = false;
    break;

Will raise a PR for it. Feedback Welcome.

**Comment by cinemast** [comment]
I am looking forward to it.

**Comment by rangatce** [comment]
PR #271 merged to develop branch. Commit https://github.com/cinemast/libjson-rpc-cpp/commit/f1d52372b8555112e3cd07cb6b69222c84e5c9ae
