### ISSUE TITLE
Threads and their purpose?

### ISSUE THREAD

**Issue by stefanpoeter** [cinemast/libjson-rpc-cpp#276]
Hi everyone,

I've setup the libjson-rpc-cpp library for my project using unix sockets only and it is working like a charm. Thanks for your effort. 

I've inspected the threads that are generated and could for one not distinguish the single threads. So naming the threads would be a cool feature. But mainly I was wondering because I was expecting two threads (one for the main application and one for the unix domain socket started with one thread). Why do I see three threads?

Thanks for your time.

Cheers
Stefan

**Comment by cinemast** [comment]
Hi Stefan!

The threads are not spawned from the library itself, but rather from their connectors. So it is very different for each connector. libmircohttpd for example opens a thread pool with multiple threads for connection handling.
