### ISSUE TITLE
HttpClient::SendRPCMessage() throws ERROR_RPC_INTERNAL for successful HTTP responses

### ISSUE THREAD

**Issue by rlebeau** [cinemast/libjson-rpc-cpp#278]
`HttpClient::SendRPCMessage()` throws an `ERROR_RPC_INTERNAL` exception on all HTTP 2xx responses other than 200:

```
  long http_code = 0;
  curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);

  if (http_code != 200) {
    throw JsonRpcException(Errors::ERROR_RPC_INTERNAL_ERROR, result);
  }
```

A user is experiencing a situation where an RPC server is returning a 201 response, see https://stackoverflow.com/questions/57492037/.  The request is successful, but `SendRPCMessage()` fails.

The check of the `http_code` value should be more like this instead:

```
  if ((http_code / 100) != 2)
```

**Comment by cinemast** [comment]
Totally agree, thanks for the report.
