### ISSUE TITLE
FileDescriptorServer missing in Homebrew Package

### ISSUE THREAD

**Issue by albertschulz** [cinemast/libjson-rpc-cpp#282]
Hi there,
I just installed the lib through homebrew, but in the current version, FileDescriptorServer is not existent, although I installed the latest version 1.2.0.
Is that the supposed behavior? If so, why isnt it included?

**Comment by cinemast** [comment]
Hi! It is a third party contribution and I don't consider it stable enough. Only Http Client/Server are supported by myself. Redis connectors have proven to work very stable too, so these are also included by default.
