### ISSUE TITLE
libjson-rpc-cpp-2, CMake 3.2.0, configure(visual studio 2013 win64), configuring incomplete with errors 

### ISSUE THREAD

**Issue by Linford1liu** [cinemast/libjson-rpc-cpp#287]
libjson-rpc-cpp-2, CMake 3.2.0, configure(visual studio 2013 win64), configuring incomplete, errors occurred as below, how do I fix this, could you please advise? thanks!

CMake Error at src/test/CMakeLists.txt:17 (find_package):
  Could not find a package configuration file provided by "jsoncpp" with any
  of the following names:

    jsoncppConfig.cmake
    jsoncpp-config.cmake
libjson-rpc-cpp-2, CMake 3.2.0, Configure (visual studio 12 2013 win64), configuring incomplete, errors occurred below, how do I fix this, could you please advise, thanks!
  Add the installation prefix of "jsoncpp" to CMAKE_PREFIX_PATH or set
  "jsoncpp_DIR" to a directory containing one of the above files.  If
  "jsoncpp" provides a separate development package or SDK, be sure it has
  been installed.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CATCH_INCLUDE_DIR
   used as include directory in directory C:/Users/lliu/Desktop/libjson-rpc-cpp-2/src/test

**Comment by cinemast** [comment]
Windows is currently not supported by this library. There is a rewrite that does support windows: https://github.com/jsonrpcx/json-rpc-cxx
