### ISSUE TITLE
Arch Linux AUR package is extremely out of date

### ISSUE THREAD

**Issue by jeremiah-miller** [cinemast/libjson-rpc-cpp#291]
I'm guessing this isn't a huge deal since the [-git version](https://aur.archlinux.org/packages.php?ID=438998) can still be installed, but the [regular package](https://aur.archlinux.org/packages.php?ID=438999) was flagged as out of date over 2 years ago, on 2018-02-02, and hasn't been updated. Just wanted to give a heads up, since the installation instructions for arch linux recommend the non-git version of the package

**Comment by cinemast** [comment]
Thanks for pointing that out, I will try to spin up an arch box and update that.

**Comment by cinemast** [comment]
I updated the regular package https://aur.archlinux.org/cgit/aur.git/commit/?h=libjson-rpc-cpp&id=85605123bab0f7b8dd4ac6af50911e35b0ec9892
