### ISSUE TITLE
Any way to enable logging what the server receives and sends?

### ISSUE THREAD

**Issue by dom11990** [cinemast/libjson-rpc-cpp#294]
I was wondering if it was possible via a define or some other flag, to enable the server to log all requests (valid and malformed) to a file or std out? If not, would this be a feature you think wold be worthwhile including? I would be willing to implement it.

**Comment by cinemast** [comment]
You can just subclass one of the existing connectors and wrap the send/receive methods with logging statements in your override function.

**Comment by dom11990** [comment]
Thanks for the speedy reply. Yes this was my plan but though something deeper that affects all the connectors could be worthwhile.

**Comment by dom11990** [comment]
Actually, I noticed that a number of the functions needed (CleanClose) are private in the tcp connectors. This means I basically have to copy paste the entire class to add the logging. Would it make sense to make these functions protected so enable simpler subclassing for use cases such as mine?

**Comment by cinemast** [comment]
Definitely, could you prepare a PR?

**Comment by dom11990** [comment]
Yup will take care of it

**Comment by dom11990** [comment]
How would you prefer I accomplish this? I was thinking:
1: move all private functions from the server and client connectors to protected
2: move private variables also to protected

Some people are real picky about that second point, preferring getters/setters. I personally wouldn't care to do this in this particular instance since the structures involved are very simple. Having the private variables exposed to the subclasses would allow specific protocols to be implemented on top of the existing transport layers (for example TCP netstrings instead of using 0xA for termination). Thoughts?

**Comment by cinemast** [comment]
Sounds perfect. No worries about protected vars.
