### ISSUE TITLE
Is there a way to enable IPV6 in tcp server, but not http server

### ISSUE THREAD

**Issue by matiscin** [cinemast/libjson-rpc-cpp#306]
As title, thanks.

We use tcp server in a very small in house application, we dont use http server. But we want to enable ipv6. What is the purpose of http server and does it run in separated process?

Thanks again.

**Comment by cinemast** [comment]
No, the HttpServer runs within the same process using libmicrohttpd. The provided connectors are just examples, feel free to modify or derive new connectors in any way you want.
