### ISSUE TITLE
Open-RPC

### ISSUE THREAD

**Issue by xloem** [cinemast/libjson-rpc-cpp#307]
The [openrpc](https://open-rpc.org/getting-started) api specification format is similar to but not quite the same as the json input to the stub generator.  Any thoughts on making small changes to be compatible with openrpc?  (Edit: thanks for your response.  I'm not using this library any more right now, but could return some day.)

**Comment by cinemast** [comment]
In a backwards compatible way, why not. The stubgen however should still accept the original version. I would be happy to receive a PR in this regard.

**Comment by cinemast** [comment]
Feel free to reopen in case there are updates on this.
