### ISSUE TITLE
Unable to build on windows because of reference to unistd.h

### ISSUE THREAD

**Issue by noodlecollie** [cinemast/libjson-rpc-cpp#314]
I don't know whether I might be doing something wrong here, but I'm executing the following command to try and build static and shared libraries for libjson-rpc-cpp 1.4.1 on Windows:

```
cmake "-DCMAKE_PREFIX_PATH=C:\my\path\to\jsoncpp" -DBUILD_STATIC_LIBS=TRUE -DBUILD_SHARED_LIBS=TRUE
  -DREDIS_SERVER=FALSE -DREDIS_CLIENT=FALSE -DHTTP_SERVER=FALSE -DHTTP_CLIENT=FALSE -DCOMPILE_STUBGEN=FALSE ..

cmake --build . --config Debug
```

When I build, I get the following errors:

```
C:\libjson-rpc-cpp-1.4.1\src\jsonrpccpp\common\streamreader.cpp(4,10): fatal error C1083: Cannot
 open include file: 'unistd.h': No such file or directory [C:\libjson-rpc-cpp-1.4.1\build\src\js
onrpccpp\common.vcxproj]
C:\libjson-rpc-cpp-1.4.1\src\jsonrpccpp\common\streamwriter.cpp(2,10): fatal error C1083: Cannot
 open include file: 'unistd.h': No such file or directory [C:\libjson-rpc-cpp-1.4.1\build\src\js
onrpccpp\common.vcxproj]
```

It appears that `unitstd.h` is being referenced by the common stream reader and writer files. I don't really know the details about how those classes work, but it appears that code that's supposed to be for Linux or UNIX (it makes reference to file descriptors) is being included in the set of files compiled for Windows.

**Comment by cinemast** [comment]
Hi! I currently do not support windows. The [new library](https://github.com/jsonrpcx/json-rpc-cxx) however does support windows
