### ISSUE TITLE
Exception -32003 : Client connector error: libcurl error: 60

### ISSUE THREAD

**Issue by CryptoCoinLab** [cinemast/libjson-rpc-cpp#319]
I setup a http server with ssl :

```
...
    m_pHttpServer = new HttpServer(port, "server.crt", "server.key");
    m_pGateServer = new GateService(db ,*m_pHttpServer);
...
```

  then connent it through httpclient:

```
    HttpClient client("https://localhost:8555");
    Client c(client);

   void callMethod(string command,Json::Value params)
   {
	Json::Value root = c.CallMethod(command.c_str(), params);
	cout << root.asString() << endl;
   }
   ...
   callMethod("start",params);
  ...
```
   I got  Exception -32003 : Client connector error: libcurl error: 60 on line 

`Json::Value root = c.CallMethod(command.c_str(), params);`

  According to https://curl.se/libcurl/c/libcurl-errors.html 

  libcurl error: 60 means  CURLE_PEER_FAILED_VERIFICATION (60)

` The remote server's SSL certificate or SSH md5 fingerprint was deemed not OK. This error code has been unified with CURLE_SSL_CACERT since 7.62.0. Its previous value was 51.`

   However，I confirm the centification server.crt was bought from SSL provider,  and my website is also using it.  

   How to fix ?

**Comment by cinemast** [comment]
Well I am pretty sure that the `server.crt` does not include `localhost` as a common name if it was provided from an official CA.

See here: https://www.baeldung.com/linux/openssl-extract-certificate-info#1-extracting-the-subject

**Comment by CryptoCoinLab** [comment]
Thank you, so I see.   How to avoid such checks ?
