### ISSUE TITLE
Ubuntu package old

### ISSUE THREAD

**Issue by StefanGu65** [cinemast/libjson-rpc-cpp#321]
Hello,

I tried to use apt-get in Ubuntu 18 LTS, and I could install a version of the package.
However, the package seems very old and is missing most of the connectors (like TCP). Hence it will not compile as an ubuntu app.

The app builds just fine in Yocto (jellyfish etc.), that uses the latest git version in the recipe. 

Is there a way to get this updated, Or do I manually have to use git to get the latest package?
The general build instructions are a bit unclear.

Stefan

**Comment by cinemast** [comment]
The Ubuntu/Debian packages are quite outdated. Latest releases are available via GitHub. 
Which part is unclear about the [build instructions](https://github.com/cinemast/libjson-rpc-cpp#build-from-source)?

**Comment by StefanGu65** [comment]
The default build is very restrictive and only builds a narrow set of options. 
A note saying this and a pointer to adjust the Cmake options would be appreciated, as this task is done infrequently and one tends to forget that between platforms.
