### ISSUE TITLE
Auth Field Setting

### ISSUE THREAD

**Issue by giuseppedevito** [cinemast/libjson-rpc-cpp#322]
I'm trying to use the client lib to interoperate with the JSON-RPC-2.0 Zabbix API; this one requires this format
`{
    "jsonrpc": "2.0",
    "method": "host.get",
    "params": {
        "output": [
            "hostid",
            "host"
        ],
        "selectInterfaces": [
            "interfaceid",
            "ip"
        ]
    },
    "id": 2,
    "auth": "0424bd59b807674191e7d77572075f33"
}`
where, as you can see at the last attribute, auth field is used. 
I've seen in src/jsonrpccpp/client/rpcprotocolclient.cpp +19 that the macro 
`const std::string RpcProtocolClient::KEY_AUTH = "auth";`
has been created but is never used.
How can I use the auth field in the request building process?

**Comment by cinemast** [comment]
That is actually a leftover from an older non-spec compliant version. JSON-RPC does not specify an `auth` field. 
However, it should be fairly easy to patch that in. But it is not supported at the moment.

If you take a look at the new implementation -> https://github.com/jsonrpcx/json-rpc-cxx/blob/master/include/jsonrpccxx/client.hpp#L41

Just add another parameter auth, inject it to the json fields and you are done.

**Comment by giuseppedevito** [comment]
Unfortunately auth can't be inside the params object. I resolved the issue implementing my own Client and RpcProtocol
that I share in this post. Since I need to be outside of your package (classes must be in my src tree) and since on Debian rpcprotocolclient.h is not inside include files installed /usr/include/libjsonrpc I've been forced to re-implement all methods without the possibility to simply inherit from your classes.
[jsonrpc-gdevito-classes.zip](https://github.com/cinemast/libjson-rpc-cpp/files/9130855/jsonrpc-gdevito-classes.zip)
I can close the issue. Thank you.
