### ISSUE TITLE
Make file has variables set to not found

### ISSUE THREAD

**Issue by Sumair-Aslam** [cinemast/libjson-rpc-cpp#323]
Im facing this problem when trying to run cmake .. && make 
![Screenshot from 2022-08-29 11-17-16](https://user-images.githubusercontent.com/80763643/187379444-49c65148-7b47-4b7a-a0aa-5e4d70e78624.png)

**Comment by laudrup** [comment]
Have you followed [this step](https://github.com/cinemast/libjson-rpc-cpp#install-the-dependencies) from the documentation?

**Comment by cinemast** [comment]
Looks like what @laudrup  said.
