### ISSUE TITLE
Cmake error..

### ISSUE THREAD

**Issue by Saikatsaha1996** [cinemast/libjson-rpc-cpp#324]
Can't complete cmake getting error..
![Screenshot_2022-09-23-12-41-41-637_com termux](https://user-images.githubusercontent.com/72664192/191908924-f857943e-7dbc-405b-a870-81790d941c90.jpg)

**Comment by cinemast** [comment]
You are missing the required dependencies. Either deactivate the modules or install them. 

Please follow the installation instructions:
https://github.com/cinemast/libjson-rpc-cpp#install-the-dependencies

**Comment by Saikatsaha1996** [comment]
> You are missing the required dependencies. Either deactivate the modules or install them.
> 
> Please follow the installation instructions: https://github.com/cinemast/libjson-rpc-cpp#install-the-dependencies

Some error solved with dep , I already installed all dep
But still getting error help please

![Screenshot_2022-09-23-16-32-50-743_com termux](https://user-images.githubusercontent.com/72664192/191947256-57fc25e4-95ce-4f5c-8920-cf1af1aba8f1.jpg)

**Comment by cinemast** [comment]
If you read the error message, you can see that CMake does not find argtable.

**Comment by Saikatsaha1996** [comment]
> 

I already installed argtable3 
https://github.com/argtable/argtable3
