### ISSUE TITLE
jsoncpp 0.7.1 changed include root directory

### ISSUE THREAD

**Issue by LefterisJP** [cinemast/libjson-rpc-cpp#80]
Hello,

There was a new release of the `jsoncpp` library which changed, among other things, the include root directory. 

As you can see on [their page](https://github.com/open-source-parsers/jsoncpp) the way to include the headers now is to change from `jsoncpp/json/json.h` to `json/json.h`

Slowly, as the new version appears in the various Operating systems there will be build errors. I was one of the first to notice it since the upgrade has already happened in ArchLinux which is the OS I am using.

**Comment by cinemast** [comment]
Thanks for the heads up. I will fix that soon.

**Comment by cinemast** [comment]
This is now fixed in 40183c5864fc7497098dd0596be89ad62a6bf198

I will try to update the package on AUR asap. Currently I am having troubles with the Boost unit testing framework there. The tests no longer compile with Boosts 1.57.

**Comment by cinemast** [comment]
Raised a bug about this on the Arch Boost package: https://bugs.archlinux.org/task/43531?project=1&cat[0]=2&string=boost

**Comment by cinemast** [comment]
Fixed and uploaded a new package to AUR: https://aur.archlinux.org/packages/libjson-rpc-cpp/
