### ISSUE TITLE
About SSL  MHD StartListening()?

### ISSUE THREAD

**Issue by alt1972** [cinemast/libjson-rpc-cpp#82]
***The call MHD_start_daemon() with SSL  just have MHD_USE_SELECT_INTERNALLY option without MHD_OPTION_THREAD_POOL_SIZE, is this correct?

Note that call to start_daemon have two MHD_OPTION_END instead MHD_OPTION_THREAD_POOL_SIZE.

```cpp
this->daemon = MHD_start_daemon(MHD_USE_SSL | MHD_USE_SELECT_INTERNALLY, this->port, NULL, NULL, HttpServer::callback, this, MHD_OPTION_HTTPS_MEM_KEY, this->sslkey.c_str(), MHD_OPTION_HTTPS_MEM_CERT, this->sslcert.c_str(), MHD_OPTION_END, this->threads, MHD_OPTION_END);
```

***The call MHD_start_daemon() without SSL have the two options  MHD_USE_SELECT_INTERNALLY+MHD_OPTION_THREAD_POOL_SIZE

**By other hand.
The client/server socket connector has dissapeared in versions  0.4.x  :-(

Regards,

**Comment by cinemast** [comment]
Thank you for reporting. This was an error yes.

About the socket connectors, they were inherently insecure and buggy, that's why I removed them since v0.4.

If someone comes up with a more clean and secure implementation, I will be happy to merge them back in again.
