### ISSUE TITLE
No support for x86_64 in cmake.

### ISSUE THREAD

**Issue by belussi** [cinemast/libjson-rpc-cpp#86]
There is no /usr/lib64 and /usr/local/lib64 paths in Find*.cmake files. Sources are compiled for x86 machines but objects are linked with x86_64 libraries. Please add "-m64" flag to cmake.

**Comment by cinemast** [comment]
What makes you think the library is compiled for x86 on a 64-bit machine?

The following command gives 64-bit:

```sh
file libjsonrpccpp-common.so.0.4.2
libjsonrpccpp-common.so.0.4.2: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2df63b9bb509b1ff11a5ccdcc13a424b4156cd58, not stripped
```
