### ISSUE TITLE
do libjson-rpc-cpp support concurrency deal? 

### ISSUE THREAD

**Issue by zhang007z** [cinemast/libjson-rpc-cpp#91]
for example:
a lot of the front-end web client by using stubclient.js  send rpc command to after-end of libjson-rpc-cpp. because there are many client, I don't know that whether  libjson-rpc-cpp support high  concurrency in same time.

Thank you for taking the time to answer my questions.

**Comment by cinemast** [comment]
Hi zhang!

I am not sure if I understood your question entirely. If you are asking if this framework supports concurrent requests, the answer is yes. There is a parameter in HttpServer connector which specifies how many concurrent threads, the server will be able to handle.

https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/server/connectors/httpserver.h#L50

Default is 50 concurrent threads.

Please close the issue, if your question has been answered.

**Comment by zhang007z** [comment]
first issue:
To existing this case, if  50  clients  send the rpc requestes to  libjson-rpc-cpp for processing at same time,then at this time the 51st client send the request to libjson-rpc-cpp, in this case do not know if libjson-rpc-cpp crash? 
second issue:
extra 50 clients call rpc function at same time.I don't know that whether this rpc processing is thread safe?

**Comment by cinemast** [comment]
1.) No it won't crash. The 51st client will have to wait until one thread is free again.
2.) This depends whether or not the procedures you are calling are thread safe. This has nothing to do with json-rpc, but is rather an application issue, see here: http://en.wikipedia.org/wiki/Thread_safety

**Comment by zhang007z** [comment]
thank you for answering my question. I close this issue.
