### ISSUE TITLE
Cannot install the lib with the apt-get on Ubuntu 14.04

### ISSUE THREAD

**Issue by malirod** [cinemast/libjson-rpc-cpp#93]
Output:
E: Unable to locate package libjsonrpccpp-dev
E: Unable to locate package libjsonrpccpp-tools

**Comment by cinemast** [comment]
Yes, the README says it works for Debian, not Ubuntu. They have not been ported yet. 

However you can download the packages manually from Debian: https://packages.debian.org/source/sid/libjson-rpc-cpp.

Or build the framework on your own.

Please close the issue if this solves your problem.

**Comment by malirod** [comment]
:+1:
