### ISSUE TITLE
cmake unconditionally checks for dependencies

### ISSUE THREAD

**Issue by malirod** [cinemast/libjson-rpc-cpp#94]
E.g. there is no way to build the sever without microhttp lib installed. cmake complains about missing headers even if the usage of the microhttp was disabled with the -DHTTP_SERVER=NO.

**Comment by cinemast** [comment]
I will check on that. Thank you for reporting.

**Comment by cinemast** [comment]
This should be fixed in f97adc755eb1373e954121f98f3e801bbba8bb21.

Please close the issue if you think it is fixed.

**Comment by malirod** [comment]
In my case this fix is good. But I've tested only the case when there is no libmicrohttpd (fix the typo in the lib name in the READMY.md, libmi**t**crohttpd). I didn't check the cases when libcurl or libargtable are missing.
