### ISSUE TITLE
Missing support of the data field in the error object

### ISSUE THREAD

**Issue by malirod** [cinemast/libjson-rpc-cpp#95]
According to the spec (http://www.jsonrpc.org/specification) the error object can contain `data`. Currently JsonRpcException allows to specify the `code` and the `message` only.

**Comment by cinemast** [comment]
You are right. pull requests are welcome. I do not know when I will have the time to fix that.

**Comment by cinemast** [comment]
I started on develop branch with this.

**Comment by cinemast** [comment]
Fixed in 61ebcd0ce7888bc51acb733b922e9a04d2bf57b1 and will be in the next release.
