### ISSUE TITLE
How can I use this library with Visual Studio 2010? 

### ISSUE THREAD

**Issue by sztomi** [cinemast/libjson-rpc-cpp#97]
As in the title, I would like to build the library with Visual Studio 2010, preferably statically. I found the dependencies zip, but I don't know where to place it so that cmake will find them.

**Comment by cinemast** [comment]
I don't think that the precompiled dependencies will work with Visual Studio 2010. They were created using MinGW.

If you use MinGW drop the win32-deps folder into the root directory of the project. As described here: https://github.com/cinemast/libjson-rpc-cpp#install-the-dependencies

**Comment by cinemast** [comment]
Please close this issues if your question is answered.

**Comment by sztomi** [comment]
Oh sorry, I did not realize I could close it. Yes, my question was answered although I'm a bit sad to hear that the library is not compatible with MSVC at the moment (I can understand why, I tried compiling the dependencies with MSVC and it's a mess).

**Comment by cinemast** [comment]
Well according to @debris it is working with MSVC. He is using it in the etherum project. Maybe he can help you with that.

**Comment by debris** [comment]
hi @sztomi.
Latest version - 4.2 is compatible with MSVC. If you need only the precompiled json-rpc library, you can download it from [our build server](https://build.ethdev.com/builds/windows-precompiled/json-rpc-cpp-4.2.tar.gz). Unfortunately, we don't have any build script([yet](https://github.com/ethereum/cpp-ethereum/issues/770)) to automatically build it from scratch.

But if you really need it, I can find time next week (wednesday, thursday or friday), to prepare it for you (with you?).

btw. @cinemast , would you accept pull request building lijson-rpc-cpp library using [`ExternalProject_Add`](http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html). We are doing this in our project for MSVC. It works pretty good. We are using [this script](https://github.com/ethereum/cpp-ethereum/blob/develop/extdep/eth_download.cmake)

**Comment by cinemast** [comment]
@debris: Yes of course. Everything that makes this project more usable is fine. 
Thanks again.

**Comment by sztomi** [comment]
Hello @debris,
That sounds great and I'll gladly help. Unfortunately for the moment I had to set aside this task and work on a more urgent one. This might go on for a few days. Is there a way we can exchange contact information? My email address is set to public on github, but I'm not sure where it is visible. If you see it, please contact me when you have time and outline the tasks that you need help with.

**Comment by debris** [comment]
Unfortunately, I don't know, where to look for the github email :/ Just email me. marek@ethdev.com

**Comment by adliner** [comment]
Hi @debris,
first, thanks for your previous contribution. I would like to use libjson-rpc-cpp in project that is being developed in VS2015 environment. I used precompiled binaries from: https://build.ethdev.com/builds/windows-precompiled/ but unfortunately they are compiled using VS2013 (__MSC_VER=1800) and hence I can't link these.

I noticed that on ethereum github @chfast came up with some commits to provide support for building dependencies in VS2015.

Could you share VS2015 libjson-rpc-cpp binaries please? I would really appreciate your help :) Perhaps you could also share VS project.solution produced by cmake in your environment? SO that i could be used more wide spread among the others.

Thanks!

**Comment by chfast** [comment]
Hi there,

- you can find scripts for building the libraries in https://github.com/ethereum/cpp-dependencies, some of them were ported to cmake scripts, but actually not libjson-rpc-cpp nor libjsoncpp;
- we keep the prebuilt libraries in GH releases: https://github.com/ethereum/cpp-dependencies/releases, you should find versions for Visual Studio 2015 easily there -- they are built for x64 and non-debug C++ runtime only.

**Comment by adliner** [comment]
Yep, I've noticed the scripts - now working to run them...

Regarding the binaries, I took these: https://github.com/ethereum/cpp-dependencies/releases/tag/vc140 and got them working, unfortunately, just like you said, these are only available for x64 & release CRT. Thank you anyway!

Are you aware if there is any effort underway to provide Visual Studio support for libjson-rpc-cpp?  The project looks great but setting in up for VS brings pain :)

**Comment by adliner** [comment]
Just for the record, I finally managed to build the lib using scripts from ethereum project. I built the full set of Debug[x86/x64] & Release[x86/x64] with VS2015. I can share the binaries if anyone cares :)

**Comment by glongoni** [comment]
Hi @adliner, if you could share the binaries built whit vs2015 it would be great :)

**Comment by chic-yong** [comment]
Hi adliner, can you share the binaries built with vs2015 to me thanks.

**Comment by liulinfeng918** [comment]
Hi @adliner, could you please share the binaries built with vs2015 to me? thank you very much
