### ISSUE TITLE
Project should have possibility to build static or shared libraries independently

### ISSUE THREAD

**Issue by tymonx** [cinemast/libjson-rpc-cpp#99]
Current:
* project builds both shared and static libraries

Expected:
* project should have possibility to choose between building shared or static libraries. Hint: use CMake built-in variable BUILD_SHARED_LIBS.

Reason:
* GCC linker prefer shared libraries over static on default when both libraries type are present. In some configuration more preferable is using static library without changing compilation flags.

**Comment by debris** [comment]
:+1: I agree
:+1: I didn't know about `BUILD_SHARED_LIBS` variable

**Comment by debris** [comment]
@cinemast what is the deadline for `0.5`? If it's more than 2 weeks, you can add it to the Milstone, and I will take care of it.

**Comment by cinemast** [comment]
There is no deadline. Thanks for contributing this. Please also keep in mind the travis integration for this.

**Comment by mgorny** [comment]
@debris, are you working on this? I'd be happy to get rid of static libraries too.

**Comment by mgorny** [comment]
Anyway, included that in my big #100 :).

**Comment by cinemast** [comment]
Fixed in 0.5.0.
